/**
 * Scorecard writer.
 *
 * The plan's Phase 0 gate asks for reproducible evidence: a recorded snapshot,
 * the commands, the environment, the provider configuration, and the
 * outstanding failures with an owner. That is exactly what last-run.md is.
 */
import { writeFileSync } from "node:fs";
import type { ScenarioOutcome } from "./harness.ts";

export interface RunMeta {
  /** Product defects the suite already knows about and routes around. */
  knownFindings: string[];
  runId: string;
  startedAt: string;
  seconds: number;
  apiBase: string;
  modelLabel: string;
  gitRevision: string;
  concurrency: number;
  selection: string;
  /** Wall-clock ceiling for the run, in minutes. Caps retry growth. */
  budgetMinutes: number;
  /** True when the ceiling was reached and retries were stopped early. */
  budgetExhausted: boolean;
  leftovers: string[];
  teardownProblems: string[];
}

const ICON: Record<ScenarioOutcome["status"], string> = {
  pass: "PASS",
  fail: "FAIL",
  "soft-fail": "SOFT",
  error: "ERR ",
};

/**
 * Tries column: whole-scenario attempts, and how many individual turns had to
 * be re-sent because the model was unreachable. A row reading `1 (+2 re-send)`
 * passed first time but only after the provider was asked three times — which
 * is the difference between a healthy provider and a rate-limited one, and the
 * reason a scorecard with no hard failures can still be worth a second look.
 */
function tries(r: ScenarioOutcome): string {
  return `${r.attempts}${r.modelRetries ? ` (+${r.modelRetries} re-send)` : ""}`;
}

function table(rows: ScenarioOutcome[]): string {
  const lines = [
    "| | Scenario | Sev | Tags | Secs | Tries | Detail |",
    "| --- | --- | --- | --- | --- | --- | --- |",
  ];
  for (const r of rows) {
    const detail = r.detail.replace(/\|/g, "\\|").replace(/\n/g, " ").slice(0, 220);
    lines.push(
      `| ${ICON[r.status]} | \`${r.id}\` | ${r.severity} | ${r.tags.join(", ")} | ${r.seconds} | ${tries(r)} | ${detail} |`,
    );
  }
  return lines.join("\n");
}

export function renderReport(outcomes: ScenarioOutcome[], meta: RunMeta): string {
  const count = (s: ScenarioOutcome["status"]): number => outcomes.filter((o) => o.status === s).length;
  const hardFails = outcomes.filter((o) => o.status === "fail");
  const softFails = outcomes.filter((o) => o.status === "soft-fail");
  const errors = outcomes.filter((o) => o.status === "error");
  const retried = outcomes.filter((o) => o.attempts > 1 || o.modelRetries > 0);

  const out: string[] = [];
  out.push("# Assistant release scenario suite — last run");
  out.push("");
  out.push("Generated by `node e2e/assistant-scenarios/run.ts`. Overwritten on every run.");
  out.push("");
  out.push("| | |");
  out.push("| --- | --- |");
  out.push(`| Started | ${meta.startedAt} |`);
  out.push(`| Wall clock | ${meta.seconds}s |`);
  out.push(`| Run id | \`${meta.runId}\` |`);
  out.push(`| Git revision | \`${meta.gitRevision}\` |`);
  out.push(`| API base | ${meta.apiBase} |`);
  out.push(`| Model | ${meta.modelLabel} |`);
  out.push(`| Concurrency | ${meta.concurrency} |`);
  out.push(`| Selection | ${meta.selection} |`);
  out.push(
    `| Time budget | ${meta.budgetMinutes}m${meta.budgetExhausted ? " — **EXHAUSTED**, retries stopped early" : ""} |`,
  );
  out.push(`| Model re-sends | ${outcomes.reduce((n, o) => n + o.modelRetries, 0)} |`);
  out.push("");
  out.push(
    `**${count("pass")} pass · ${count("fail")} hard fail · ${count("soft-fail")} soft fail · ` +
      `${count("error")} error** (of ${outcomes.length})`,
  );
  out.push("");
  out.push(
    "A hard failure blocks release: permissions, data leakage, duplicated effects, unconfirmed " +
      "destruction, unrequested writes. It is only ever recorded on POSITIVE EVIDENCE of a violation — " +
      "a row that was written, a title that leaked, a delete that happened without a confirmation. " +
      "A soft failure is live-model nondeterminism — it was retried once and is reported, not enforced. " +
      "An **error** is inconclusive: the model was unreachable even after re-sends, or a precondition " +
      "(the setup step the assertion needs) never materialised. Inconclusive is never a release blocker, " +
      "and never evidence that the product is correct either.",
  );
  out.push("");

  if (hardFails.length) {
    out.push("## Hard failures (release blockers)");
    out.push("");
    for (const f of hardFails) out.push(`- \`${f.id}\` — ${f.title}\n  - ${f.detail}`);
    out.push("");
  }
  if (errors.length) {
    out.push("## Inconclusive (harness / precondition)");
    out.push("");
    out.push("Neither a pass nor a violation: the assertion never ran.");
    out.push("");
    for (const f of errors) out.push(`- \`${f.id}\` — ${f.detail}`);
    out.push("");
  }
  if (softFails.length) {
    out.push("## Soft failures (model nondeterminism / product gaps to triage)");
    out.push("");
    for (const f of softFails) out.push(`- \`${f.id}\` — ${f.title}\n  - ${f.detail}`);
    out.push("");
  }

  out.push("## Scorecard");
  out.push("");
  out.push(table(outcomes));
  out.push("");

  out.push("## Tool chains");
  out.push("");
  out.push("One line per assistant turn, in the order the scenario ran them.");
  out.push("");
  out.push("```");
  for (const o of outcomes) {
    if (!o.chains.length) {
      out.push(`${o.id}: (no model turn)`);
      continue;
    }
    o.chains.forEach((chain, i) => out.push(`${o.id} [${i + 1}]: ${chain || "(no tools)"}`));
  }
  out.push("```");
  out.push("");

  if (retried.length) {
    out.push("## Retried");
    out.push("");
    out.push(
      retried
        .map((r) => `\`${r.id}\` (${r.attempts} attempts${r.modelRetries ? `, ${r.modelRetries} model re-send` : ""}, ${r.status})`)
        .join(", "),
    );
    out.push("");
  }

  if (meta.knownFindings.length) {
    out.push("## Known product findings this suite routes around");
    out.push("");
    out.push("Recorded so the scorecard is honest about what it is *not* asserting.");
    out.push("");
    for (const f of meta.knownFindings) out.push(`- ${f}`);
    out.push("");
  }

  out.push("## Data left behind");
  out.push("");
  if (meta.teardownProblems.length) {
    out.push("Teardown reported problems — these rows may still exist:");
    out.push("");
    for (const p of meta.teardownProblems) out.push(`- ${p}`);
    out.push("");
  }
  for (const l of meta.leftovers) out.push(`- ${l}`);
  out.push("");
  return out.join("\n");
}

export function writeReport(path: string, body: string): void {
  writeFileSync(path, body, "utf8");
}
