"use client";

import { useEffect, useState } from "react";
import { useQuery, useQueryClient, useMutation } from "@tanstack/react-query";
import { Sparkles, Plus, Bot, User, Loader2, FlaskConical, Play, CircleStop, Check, X, Film, ListChecks, RotateCcw, Bug, MoreHorizontal } from "lucide-react";
import { toast } from "sonner";
import { api } from "@agora/core/api";
import { useWorkspaceId } from "@agora/core/hooks";
import { agentTaskSnapshotKeys } from "@agora/core/agents";
import { issueKeys, issueDetailOptions, testCasesOptions } from "@agora/core/issues/queries";
import type { TestCase } from "@agora/core/types";
import { CASE_TEMPLATES, type CaseTemplate } from "@agora/core/qa/templates";
import { parseStepResults } from "@agora/core/qa/step-run";
import { Button } from "@agora/ui/components/ui/button";
import { Input } from "@agora/ui/components/ui/input";
import { Textarea } from "@agora/ui/components/ui/textarea";
import {
  DropdownMenu,
  DropdownMenuTrigger,
  DropdownMenuContent,
  DropdownMenuItem,
} from "@agora/ui/components/ui/dropdown-menu";
import { cn } from "@agora/ui/lib/utils";
import { useT, useTimeAgo } from "../../i18n";
import {
  PriorityToggle,
  ModalityToggle,
  priorityRank,
  priorityChipClass,
  usePriorityLabel,
  useModalityLabel,
  type TestCasePriority,
  type TestCaseModality,
} from "./case-meta";
import { useRunningTestCaseId, useLiveCaseVerdicts, useQaRunningTasks } from "./qa-live-progress";
import { StepEditor, StepList, parseSteps, serializeSteps, type ParsedStep } from "./step-editor";
import { StepRunChecklist, StepResultList } from "./step-run";
import { verdictIcon } from "./verdict";
import { FileBugSheet, type FileBugCaseSeed } from "./file-bug-sheet";

// The QA team's Test-cases instrument. Lists an issue's cases (authored by a QA
// human OR generated by a QA-Squad agent via gen_test_cases), each with its
// latest run verdict, and lets QA add cases, generate via agent, and record a
// pass/fail run. Automated execution + regression are later phases.
//
// Density note: this panel lives in a fixed 380px rail (see qa-review-page),
// same width class as the issue detail page's Properties panel — every
// control here is icon-first / single-line-per-row on purpose, not a
// scaled-down version of a wide layout. Badges became plain muted text,
// header actions became icon buttons with tooltips, and Pass/Fail became
// small icon buttons instead of text pills, all to fit without truncating
// or wrapping into a 3-line mess.

export function TestCasesPanel({ issueId }: { issueId: string }) {
  const { t } = useT("issues");
  const qc = useQueryClient();
  const wsId = useWorkspaceId();
  const { data } = useQuery(testCasesOptions(issueId));
  const cases = data?.test_cases ?? [];
  const [adding, setAdding] = useState(false);
  // Suggest-from-ticket affordance (phase 3): when the issue has a substantive
  // plan to derive from but ZERO cases yet, surface a one-click "generate from
  // the ticket" card instead of the generic empty state. Same-key query as the
  // QA lens's issue detail — a cache hit, not a second fetch. Gate on a
  // non-trivial DESCRIPTION: acceptance_criteria isn't exposed in the issue
  // response the frontend sees, and the gen_test_cases agent reads the full
  // plan (criteria included) server-side anyway. Dismissal is local state —
  // it re-offers next visit, which is fine for a suggestion.
  const { data: issueDetail } = useQuery(issueDetailOptions(wsId, issueId));
  const [suggestDismissed, setSuggestDismissed] = useState(false);
  const hasSubstantivePlan = (issueDetail?.description ?? "").trim().length >= 40;
  const showSuggest = data !== undefined && cases.length === 0 && !adding && hasSubstantivePlan && !suggestDismissed;
  // The live agent task driving this issue's QA/test run right now. `.id` is the
  // task id the cancel endpoint needs; a running row for THIS issue is the one to
  // stop. (SliceActionResponse carries no task id, so the dispatch return can't
  // be used — the snapshot is the source of truth for the live task.) Filtered
  // to the QA squad's own tasks (useQaRunningTasks) — an unrelated dev/knowledge
  // task running on the same issue must never be offered up as "the QA run" a
  // Stop click would cancel (audit finding: Stop targeted ANY running task).
  const runningTaskId = useQaRunningTasks(issueId)[0]?.id ?? null;
  // The Playwright trace viewer opens as a full-panel overlay iframe — the URL
  // is a same-origin reverse-proxy path the backend hands back per launch.
  const [traceUrl, setTraceUrl] = useState<string | null>(null);
  // The run id behind the current traceUrl, kept alongside it so the overlay's
  // retry affordance can re-fire the SAME launch mutation for the SAME run
  // without the row that originally triggered it still being mounted/visible.
  const [traceRunId, setTraceRunId] = useState<string | null>(null);
  const runningCaseId = useRunningTestCaseId(issueId);
  const liveVerdicts = useLiveCaseVerdicts(issueId);
  // Cases the user just hit "run" on — an OPTIMISTIC running marker, so the row
  // spins the instant it's clicked instead of waiting for the agent to emit its
  // `RUNNING test_case:` marker (which lags behind agent setup). Cleared on a
  // timer; the agent's own marker takes over if/when it arrives.
  const [runningLocal, setRunningLocal] = useState<Set<string>>(new Set());
  const markRunning = (id: string, on: boolean) =>
    setRunningLocal((s) => {
      const n = new Set(s);
      if (on) n.add(id);
      else n.delete(id);
      return n;
    });

  const invalidate = () => qc.invalidateQueries({ queryKey: issueKeys.testCases(issueId) });

  const generate = useMutation({
    mutationFn: () => api.generateTestCases(issueId),
    onSuccess: () => {
      toast.success(t(($) => $.test_cases.generated_toast));
      invalidate();
    },
    onError: (e) => toast.error(e instanceof Error ? e.message : "Failed"),
  });

  const runAll = useMutation({
    mutationFn: () => api.runTestCases(issueId),
    onSuccess: () => {
      toast.success(t(($) => $.test_cases.run_all_toast));
      invalidate();
    },
    onError: (e) => toast.error(e instanceof Error ? e.message : "Failed"),
  });

  // Cancel the live QA/test run. Invalidating the task snapshot refetches it so
  // the cancelled task drops out of "running" — which clears `runningTaskId`
  // here AND unmounts QALiveProgress's per-task marker watcher (its cleanup
  // resets the running-case cache to null), so the "RUNS" markers on the rows
  // clear without a manual refresh.
  const stopRun = useMutation({
    mutationFn: (taskId: string) => api.cancelTaskById(taskId),
    onSuccess: () => {
      toast.success(t(($) => $.test_cases.stopping));
      invalidate();
      void qc.invalidateQueries({ queryKey: agentTaskSnapshotKeys.list(wsId) });
      void qc.invalidateQueries({ queryKey: ["qa-running-case", issueId] });
      void qc.invalidateQueries({ queryKey: ["qa-live-case-verdicts", issueId] });
    },
    onError: (e) => toast.error(e instanceof Error ? e.message : "Failed"),
  });

  // A run is "live" for this issue if the agent task snapshot has a running task,
  // the run-all dispatch is in flight, or the live stream is naming a case under
  // test — any of the three means the QA engineer should be able to stop it.
  const runLive = runAll.isPending || !!runningCaseId || !!runningTaskId;
  const onStopRun = () => {
    if (!runningTaskId) {
      toast(t(($) => $.test_cases.stop_no_task));
      return;
    }
    stopRun.mutate(runningTaskId);
  };

  const hasAutomated = cases.some((c) => c.kind === "automated");

  // Failing / blocked float to the TOP so a reviewer sees what needs attention
  // first; passing sinks to the bottom. Sort on the PERSISTED verdict only (not
  // the live running/verdict markers) so rows don't reshuffle mid-run. Within
  // one state, priority breaks the tie (p1 before p2 before p3) — a failing p1
  // outranks a failing p3.
  const statusRank = (c: TestCase) => {
    switch (c.latest_run?.status) {
      case "fail":
        return 0;
      case "blocked":
      case "skip":
        return 1;
      case "pass":
        return 4;
      default:
        return 3; // never run
    }
  };
  const sorted = [...cases].sort(
    (a, b) => statusRank(a) - statusRank(b) || priorityRank(a.priority) - priorityRank(b.priority),
  );
  const failedCount = cases.filter((c) => c.latest_run?.status === "fail").length;

  // Records a human run verdict. `output` is optional: the one-click ✓/✗
  // sends none; a per-step checklist walk (phase 4) sends its serialized
  // breakdown so the row's expanded detail can render step-by-step results.
  const recordRun = useMutation({
    mutationFn: ({ caseId, status, output }: { caseId: string; status: "pass" | "fail" | "skip"; output?: string }) =>
      api.recordTestCaseRun(caseId, { status, output }),
    onSuccess: invalidate,
    onError: (e) => toast.error(e instanceof Error ? e.message : "Failed"),
  });

  // Run ONE case via the QA agent (scoped run_test_cases). Optimistically spins
  // that row immediately; clears after a window (the agent run is async).
  const runOne = useMutation({
    mutationFn: (c: TestCase) =>
      api.sliceAction(issueId, {
        kind: "run_test_cases",
        scope: `RUN ONLY the single test case id=${c.id} ("${c.title}") — execute just this one, skip all other cases.`,
      }),
    onMutate: (c) => {
      markRunning(c.id, true);
      // Safety clear so a stuck run never leaves the row spinning forever.
      setTimeout(() => markRunning(c.id, false), 120_000);
    },
    onSuccess: () => {
      toast.success(t(($) => $.test_cases.run_all_toast));
      invalidate();
    },
    onError: (e, c) => {
      markRunning(c.id, false);
      toast.error(e instanceof Error ? e.message : "Failed");
    },
  });

  // Re-run ONLY the currently-failing cases (Phase 2, item 4) — the scoped
  // SET form of the same dispatch. The server enforces the set fail-closed
  // (scopedTestCaseIDsFromTrigger → CaptureTestRuns drops out-of-set
  // entries), so a stray extra result can't overwrite a healthy case.
  const rerunFailed = useMutation({
    mutationFn: (ids: string[]) =>
      api.sliceAction(issueId, {
        kind: "run_test_cases",
        scope: `RUN ONLY these test cases ids=${ids.join(",")} — execute just these currently-failing cases, skip all other cases.`,
      }),
    onMutate: (ids) => {
      for (const id of ids) markRunning(id, true);
      setTimeout(() => {
        for (const id of ids) markRunning(id, false);
      }, 120_000);
    },
    onSuccess: () => {
      toast.success(t(($) => $.test_cases.run_all_toast));
      invalidate();
    },
    onError: (e, ids) => {
      for (const id of ids) markRunning(id, false);
      toast.error(e instanceof Error ? e.message : "Failed");
    },
  });

  // Per-case File-bug (Phase 2, item 5): the case whose Bug action is open,
  // or null. Conditionally mounted so the sheet's seeded title/notes compute
  // fresh per case. No issue-verdict gate — a failing case is bug-worthy
  // regardless of the overall gate verdict.
  const [bugCase, setBugCase] = useState<TestCase | null>(null);

  const launchTrace = useMutation({
    mutationFn: (runId: string) => api.launchTrace(runId),
    onMutate: (runId) => setTraceRunId(runId),
    onSuccess: (res) => {
      if (res.trace_url) setTraceUrl(res.trace_url);
      else toast.error(t(($) => $.test_cases.trace_error));
    },
    onError: (e) => toast.error(e instanceof Error ? e.message : t(($) => $.test_cases.trace_error)),
  });

  return (
    <section className="space-y-2">
      <div className="flex items-center gap-2">
        <FlaskConical className="size-4 shrink-0 text-muted-foreground" />
        <span className="text-sm font-medium">{t(($) => $.test_cases.section)}</span>
        {/* One count line — the old "N Positive · N Negative" coverage row and
            the separate attention row are merged in here: "12 · 2 failing". */}
        <span className="rounded bg-muted px-1.5 py-0.5 text-[11px] text-muted-foreground">{cases.length}</span>
        {failedCount > 0 && (
          <span className="text-[11px] font-medium text-destructive">
            · {t(($) => $.test_cases.failing_count, { count: failedCount })}
          </span>
        )}
        <div className="ml-auto flex items-center gap-1">
          {/* ONE state-aware primary: Stop (a run is live) → Re-run failed
              (something's red) → Run all. Never all three at once. */}
          {runLive ? (
            <Button
              type="button"
              size="sm"
              variant="outline"
              className="h-7 gap-1 px-2 text-[11px] text-destructive hover:bg-destructive/10 hover:text-destructive"
              disabled={stopRun.isPending}
              onClick={onStopRun}
              title={stopRun.isPending ? t(($) => $.test_cases.stopping) : t(($) => $.test_cases.stop)}
            >
              {stopRun.isPending ? <Loader2 className="size-3.5 animate-spin" /> : <CircleStop className="size-3.5" />}
              {t(($) => $.test_cases.stop_label)}
            </Button>
          ) : failedCount > 0 ? (
            <Button
              type="button"
              size="sm"
              variant="outline"
              className="h-7 gap-1 px-2 text-[11px] text-destructive hover:bg-destructive/10 hover:text-destructive"
              disabled={rerunFailed.isPending}
              onClick={() =>
                rerunFailed.mutate(cases.filter((c) => c.latest_run?.status === "fail").map((c) => c.id))
              }
              title={t(($) => $.test_cases.rerun_failed_title)}
            >
              {rerunFailed.isPending ? <Loader2 className="size-3.5 animate-spin" /> : <RotateCcw className="size-3.5" />}
              {t(($) => $.test_cases.rerun_failed, { count: failedCount })}
            </Button>
          ) : hasAutomated ? (
            <Button
              type="button"
              size="sm"
              variant="outline"
              className="h-7 gap-1 px-2 text-[11px]"
              disabled={runAll.isPending}
              onClick={() => runAll.mutate()}
              title={runAll.isPending ? t(($) => $.test_cases.running_all) : t(($) => $.test_cases.run_all)}
            >
              {runAll.isPending ? <Loader2 className="size-3.5 animate-spin" /> : <Play className="size-3.5" />}
              {t(($) => $.test_cases.run_all)}
            </Button>
          ) : null}
          {/* Generate + Add — the two constant actions, compact next to the
              labeled primary. */}
          <Button
            type="button"
            size="icon"
            variant="outline"
            className="size-7"
            disabled={generate.isPending}
            onClick={() => generate.mutate()}
            title={generate.isPending ? t(($) => $.test_cases.generating) : t(($) => $.test_cases.generate)}
          >
            {generate.isPending ? <Loader2 className="size-3.5 animate-spin" /> : <Sparkles className="size-3.5" />}
          </Button>
          <Button
            type="button"
            size="icon"
            variant="outline"
            className="size-7"
            onClick={() => setAdding((v) => !v)}
            title={t(($) => $.test_cases.add)}
          >
            <Plus className="size-3.5" />
          </Button>
        </div>
      </div>

      {adding && <AddCaseForm issueId={issueId} onDone={() => { setAdding(false); invalidate(); }} />}

      {cases.length === 0 && !adding ? (
        showSuggest ? (
          // The suggest-from-ticket card — a stronger empty state for issues
          // with a real plan: one click fires the SAME gen_test_cases slice
          // action as the header's sparkle button (affordance, not machinery).
          <div className="rounded-lg border bg-muted/20 px-3 py-3">
            <div className="flex items-start gap-2">
              <Sparkles className="mt-0.5 size-3.5 shrink-0 text-muted-foreground" aria-hidden />
              <div className="min-w-0 flex-1">
                <p className="text-[12px] font-medium">{t(($) => $.test_cases.suggest_title)}</p>
                <p className="mt-0.5 text-[11px] text-muted-foreground">{t(($) => $.test_cases.suggest_text)}</p>
              </div>
              <Button
                type="button"
                variant="ghost"
                size="icon"
                className="size-6 shrink-0 text-muted-foreground"
                onClick={() => setSuggestDismissed(true)}
                title={t(($) => $.test_cases.suggest_dismiss)}
              >
                <X className="size-3.5" />
              </Button>
            </div>
            <Button
              type="button"
              size="sm"
              className="mt-2 h-7 w-full gap-1.5 text-[12px]"
              disabled={generate.isPending}
              onClick={() => generate.mutate()}
            >
              {generate.isPending ? <Loader2 className="size-3.5 animate-spin" /> : <Sparkles className="size-3.5" />}
              {t(($) => $.test_cases.suggest_generate)}
            </Button>
          </div>
        ) : (
          <div className="rounded-lg border border-dashed bg-muted/20 px-3 py-5 text-center">
            <p className="text-[12px] text-muted-foreground">{t(($) => $.test_cases.empty)}</p>
            <p className="mt-0.5 text-[11px] text-muted-foreground/70">{t(($) => $.test_cases.empty_hint)}</p>
          </div>
        )
      ) : (
        <ul className="divide-y rounded-lg border">
          {sorted.map((c) => (
            <CaseRow
              key={c.id}
              c={c}
              busy={recordRun.isPending}
              onRun={(status) => recordRun.mutate({ caseId: c.id, status })}
              onStepRun={(status, output) => recordRun.mutate({ caseId: c.id, status, output })}
              onRunCase={() => runOne.mutate(c)}
              onFileBug={() => setBugCase(c)}
              isRunning={c.id === runningCaseId || runningLocal.has(c.id)}
              liveVerdict={liveVerdicts[c.id]}
              onViewTrace={(runId) => launchTrace.mutate(runId)}
              traceLaunchingRunId={launchTrace.isPending ? launchTrace.variables ?? null : null}
            />
          ))}
        </ul>
      )}

      {traceUrl && (
        <TraceOverlay
          url={traceUrl}
          onClose={() => {
            setTraceUrl(null);
            setTraceRunId(null);
          }}
          onRetry={traceRunId ? () => launchTrace.mutate(traceRunId) : undefined}
        />
      )}

      {/* Per-case File-bug — conditionally mounted so the seeded title/detail
          compute fresh for each case. Pre-filled with the case title, the
          failed step + human note (parsed from the latest run's checklist
          breakdown when present), and the covered criterion. No issue-level
          verdict gate. */}
      {bugCase && issueDetail && (
        <FileBugSheet
          open
          onOpenChange={(v) => {
            if (!v) setBugCase(null);
          }}
          sourceId={issueId}
          sourceTitle={issueDetail.title}
          identifier={issueDetail.identifier}
          projectId={issueDetail.project_id}
          evidence={null}
          caseSeed={buildCaseSeed(bugCase)}
        />
      )}
    </section>
  );
}

// buildCaseSeed derives the per-case FileBugSheet prefill from the case's
// latest run: a checklist walk yields "failed at step N — <note>" lines
// (parseStepResults); a free-text/agent run falls back to its lead line.
function buildCaseSeed(c: TestCase): FileBugCaseSeed {
  let detail = "";
  const output = c.latest_run?.output ?? "";
  const steps = output ? parseStepResults(output) : null;
  if (steps) {
    detail = steps
      .filter((r) => r.status === "fail")
      .map((r) => `failed at step ${r.step}${r.note ? ` — ${r.note}` : ""}`)
      .join("; ");
  }
  if (!detail && output) {
    const firstLine = output.split("\n", 1)[0]?.trim() ?? "";
    detail = firstLine.length > 200 ? `${firstLine.slice(0, 199)}…` : firstLine;
  }
  return { title: c.title, detail, criterionRef: c.criterion_ref || undefined };
}

// How long the viewer gets to render before the overlay offers a retry. A
// blank iframe from a dead reverse-proxy target still "loads" as far as the
// browser is concerned (it rendered SOME response — a connection-refused error
// page or a 502 body), so iframe onLoad/onError can't reliably detect this
// failure mode. A generous timeout is the only honest signal: if the viewer
// hasn't confirmed it's up by then, offer the escape hatch instead of leaving
// the reviewer staring at an unexplained blank panel.
const TRACE_LOAD_TIMEOUT_MS = 8000;

// Full-panel overlay hosting the real Playwright trace viewer in an iframe. The
// src is a same-origin reverse-proxy URL (behind the authed session), so the
// viewer + its DOM snapshots / screenshots stream through the backend — no
// vendored viewer, no cross-origin auth wall. Esc / the close button dismiss it.
function TraceOverlay({ url, onClose, onRetry }: { url: string; onClose: () => void; onRetry?: () => void }) {
  const { t } = useT("issues");
  const [showRetry, setShowRetry] = useState(false);

  useEffect(() => {
    setShowRetry(false);
    const timer = setTimeout(() => setShowRetry(true), TRACE_LOAD_TIMEOUT_MS);
    return () => clearTimeout(timer);
  }, [url]);

  return (
    <div className="fixed inset-0 z-50 flex flex-col bg-background">
      <div className="flex items-center gap-2 border-b px-3 py-2">
        <Film className="size-4 shrink-0 text-muted-foreground" />
        <span className="text-sm font-medium">{t(($) => $.test_cases.trace_title)}</span>
        {/* Escape hatch for the blank-panel failure mode: the viewer proxy
            couldn't reach the daemon/show-trace process. Never assumed fatal —
            just offered after a generous grace period, with a one-click retry
            that re-launches the SAME run's trace viewer. */}
        {showRetry && onRetry && (
          <span className="ml-2 flex min-w-0 items-center gap-1.5 text-[11px] text-muted-foreground">
            <span className="truncate">{t(($) => $.test_cases.trace_load_error)}</span>
            <Button
              type="button"
              variant="outline"
              size="sm"
              className="h-6 shrink-0 px-2 text-[11px]"
              onClick={() => {
                setShowRetry(false);
                onRetry();
              }}
            >
              {t(($) => $.test_cases.trace_retry)}
            </Button>
          </span>
        )}
        <Button
          type="button"
          variant="ghost"
          size="icon"
          className="ml-auto size-7"
          onClick={onClose}
          title={t(($) => $.test_cases.trace_close)}
        >
          <X className="size-4" />
        </Button>
      </div>
      <iframe
        key={url}
        src={url}
        title={t(($) => $.test_cases.trace_title)}
        className="min-h-0 flex-1 border-0"
        onLoad={() => setShowRetry(false)}
      />
    </div>
  );
}

function CaseRow({
  c,
  busy,
  onRun,
  onStepRun,
  onRunCase,
  onFileBug,
  isRunning,
  liveVerdict,
  onViewTrace,
  traceLaunchingRunId,
}: {
  c: TestCase;
  busy: boolean;
  onRun: (status: "pass" | "fail") => void;
  // Record a finished per-step manual walk (phase 4): the derived case verdict
  // plus the serialized per-step breakdown for the run's output.
  onStepRun: (status: "pass" | "fail" | "skip", output: string) => void;
  // Execute THIS one case via the QA agent (single-case run).
  onRunCase: () => void;
  // Open FileBugSheet pre-filled from THIS case (Phase 2, item 5). Offered on
  // failing/blocked rows — where a bug-worthy finding lives.
  onFileBug: () => void;
  // Open the Playwright trace viewer for this case's latest run (only wired when
  // that run captured a trace). The panel owns the overlay; the row just fires.
  onViewTrace: (runId: string) => void;
  // The run id whose trace launch is in flight (shows a spinner on that button),
  // or null. Panel-level so a second row's button isn't disabled by this one.
  traceLaunchingRunId: string | null;
  // Jest-style "RUNS <spec>" — true while the live agent stream's most recent
  // `RUNNING test_case:<id>` marker (see useRunningTestCaseId) names THIS case.
  // Takes priority over the persisted latest_run status, which is correct: a
  // case being re-run right now should show as running, not as its stale
  // previous verdict.
  isRunning: boolean;
  // Live verdict parsed from the running stream's `QA_RESULT test_case:<id>`
  // marker — the case just finished THIS run but its test_run row hasn't
  // persisted yet. Shown as ✓/✗ with a "live" pulse so the panel updates in
  // real time; superseded by the persisted status once the run ends.
  liveVerdict?: "pass" | "fail";
}) {
  const { t } = useT("issues");
  const timeAgo = useTimeAgo();
  const priorityLabel = usePriorityLabel();
  const modalityLabel = useModalityLabel();
  // Precedence: running now > this run's just-finished live verdict > persisted.
  const status = isRunning ? undefined : liveVerdict ?? c.latest_run?.status;
  const isLive = !isRunning && !!liveVerdict && liveVerdict === status && !c.latest_run;
  // "blocked"/"skip" only ever comes from the agent's run_test_cases protocol
  // (the human Pass/Fail buttons only ever write pass/fail) — it means the
  // agent attempted this case and could NOT exercise it (no reachable
  // browser, missing data/route), which reads very differently from "never
  // attempted" (no latest_run at all). c.latest_run?.output carries the
  // agent's one-line reason.
  const isBlocked = status === "blocked" || status === "skip";
  const hasReason = !isRunning && (status === "fail" || isBlocked) && !!c.latest_run?.output;
  // Jest-style: a failing/blocked case opens itself so the reason is visible
  // without an extra click — the whole point of asking "which failed and why"
  // is to NOT have to hunt for it. A passing/never-run case stays collapsed.
  const [open, setOpen] = useState(hasReason);
  // Per-step manual run (phase 4): the case's parsed steps power both the
  // interactive checklist and the recorded run's breakdown display. A manual
  // walk is offered for ANY case with steps — hand-walking an automated
  // case's steps is legitimate when its box/script is unavailable.
  const parsedSteps = parseSteps(c.steps);
  const [stepRunOpen, setStepRunOpen] = useState(false);
  // The latest run's per-step breakdown, when that run was a checklist walk
  // (null for agent free-text evidence / one-click ✓✗ runs / legacy).
  const stepResults = c.latest_run?.output ? parseStepResults(c.latest_run.output) : null;
  const kindLabel = c.kind === "automated" ? t(($) => $.test_cases.kind_automated) : t(($) => $.test_cases.kind_manual);
  const categoryLabel =
    c.category === "negative" ? t(($) => $.test_cases.category_negative) : t(($) => $.test_cases.category_positive);
  // Run history (Phase 3) — fetched only when the row is EXPANDED (the strip
  // lives in the detail); last 5, newest first from the API.
  const { data: historyData } = useQuery({
    queryKey: ["test-case-runs", c.id],
    queryFn: () => api.listTestCaseRuns(c.id),
    enabled: open,
    staleTime: 15_000,
  });
  const historyRuns = (historyData?.runs ?? []).slice(0, 5);

  // ⋯ overflow contents (each conditional). Hand-walking an automated case's
  // steps is legitimate when its box/script is unavailable, so it stays
  // reachable there rather than as the row's primary Run.
  const canHandWalk = c.kind === "automated" && parsedSteps.length > 0;
  const hasTrace = !!(c.latest_run?.trace_path && c.latest_run.id);
  const canFileBug = !isRunning && (status === "fail" || isBlocked);

  return (
    <li
      className={cn(
        "group/case relative px-3 py-2 transition-colors",
        // The case executing RIGHT NOW is unmistakable: a tinted row + a spinning
        // marker on the title + an ANIMATED border. The ring + left accent bar are
        // separate overlays so only the border animates, not the row content.
        isRunning && "bg-info/10",
      )}
    >
      {isRunning && (
        <>
          {/* Bright pulsing inset ring around the whole row… */}
          <span
            aria-hidden
            className="pointer-events-none absolute inset-0 z-10 rounded-md ring-2 ring-inset ring-info motion-safe:animate-pulse"
          />
          {/* …plus a solid accent bar down the left edge, so the eye lands on the
              running case even at a glance. */}
          <span
            aria-hidden
            className="pointer-events-none absolute inset-y-1 left-0 z-10 w-1 rounded-full bg-info motion-safe:animate-pulse"
          />
        </>
      )}
      {/* Collapsed row = [status] Title …… [Run] [⋯]. Everything else — the
          meta taxonomy, the reason, run history, steps — lives behind the row
          expand (click the title). */}
      <div className="flex items-center gap-2">
        {/* Status on the LEFT, 4-vocab: Testing (spinner) / Passed / Failed
            (also blocked+skip = couldn't run) / Not run (—). */}
        {isRunning ? (
          <Loader2 className="size-4 shrink-0 animate-spin text-info" aria-hidden />
        ) : status === "pass" ? (
          <span
            className={cn("shrink-0", isLive && "motion-safe:animate-pulse")}
            title={isLive ? t(($) => $.test_cases.runs_now) : undefined}
          >
            {verdictIcon("pass", "size-4")}
          </span>
        ) : status === "fail" || isBlocked ? (
          <span
            className={cn("shrink-0", isLive && "motion-safe:animate-pulse")}
            title={
              isLive
                ? t(($) => $.test_cases.runs_now)
                : c.latest_run?.output || (isBlocked ? t(($) => $.test_cases.blocked) : undefined)
            }
          >
            {verdictIcon("fail", "size-4")}
          </span>
        ) : (
          <span className="shrink-0 text-[10px] text-muted-foreground">—</span>
        )}
        {/* Title — click toggles the expanded detail. The ONE inline badge is a
            P1 marker on a failing P1 (the first thing a reviewer must see). */}
        <button type="button" className="min-w-0 flex-1 text-left" onClick={() => setOpen((v) => !v)}>
          <span
            className={cn("flex items-center gap-1.5 truncate text-[13px]", isRunning && "font-medium text-info")}
          >
            <span className="truncate">{c.title}</span>
            {c.priority === "p1" && (status === "fail" || isBlocked) && (
              <span className="shrink-0 rounded bg-destructive/10 px-1 text-[9px] font-medium uppercase tracking-wide text-destructive">
                {priorityLabel("p1")}
              </span>
            )}
          </span>
        </button>
        {/* Right — a running label, else the ONE primary Run + a ⋯ overflow. */}
        <div className="flex shrink-0 items-center gap-1 pt-0.5">
          {isRunning ? (
            <span className="flex items-center gap-1 text-[10px] font-medium text-info">
              <span aria-hidden className="size-1.5 shrink-0 rounded-full bg-info motion-safe:animate-pulse" />
              {t(($) => $.test_cases.runs_now)}
            </span>
          ) : (
            <>
              {/* Primary Run: agent-run for automated, the manual checklist for
                  manual. A manual case with no steps keeps an inline pass/fail —
                  the only way it can record a verdict. */}
              {c.kind === "automated" ? (
                <Button
                  type="button"
                  variant="ghost"
                  size="icon"
                  onClick={onRunCase}
                  className="size-6 text-info hover:bg-info/10"
                  title={t(($) => $.test_cases.run_case)}
                >
                  <Play className="size-3.5" />
                </Button>
              ) : parsedSteps.length > 0 ? (
                <Button
                  type="button"
                  variant="ghost"
                  size="icon"
                  onClick={() => setStepRunOpen((v) => !v)}
                  className={cn("size-6 text-info hover:bg-info/10", stepRunOpen && "bg-info/10")}
                  title={t(($) => $.test_cases.run_steps)}
                >
                  <Play className="size-3.5" />
                </Button>
              ) : (
                <div className="flex items-center gap-1">
                  <Button
                    type="button"
                    variant="ghost"
                    size="icon"
                    disabled={busy}
                    onClick={() => onRun("pass")}
                    className="size-6 text-emerald-700 hover:bg-emerald-600/10 dark:text-emerald-300"
                    title={t(($) => $.test_cases.run_pass)}
                  >
                    <Check className="size-3.5" />
                  </Button>
                  <Button
                    type="button"
                    variant="ghost"
                    size="icon"
                    disabled={busy}
                    onClick={() => onRun("fail")}
                    className="size-6 text-destructive hover:bg-destructive/10"
                    title={t(($) => $.test_cases.run_fail)}
                  >
                    <X className="size-3.5" />
                  </Button>
                </div>
              )}
              {/* Overflow ⋯ — hand-walk an automated case's steps, view its
                  trace, file a bug. Rendered only when it has an item. */}
              {(canHandWalk || hasTrace || canFileBug) && (
                <DropdownMenu>
                  <DropdownMenuTrigger
                    render={
                      <Button
                        type="button"
                        variant="ghost"
                        size="icon"
                        className="size-6 text-muted-foreground"
                        title={t(($) => $.qa_review.more_actions)}
                        aria-label={t(($) => $.qa_review.more_actions)}
                      />
                    }
                  >
                    <MoreHorizontal className="size-3.5" />
                  </DropdownMenuTrigger>
                  <DropdownMenuContent align="end">
                    {canHandWalk && (
                      <DropdownMenuItem onClick={() => setStepRunOpen((v) => !v)}>
                        <ListChecks className="size-3.5" />
                        {t(($) => $.test_cases.run_steps)}
                      </DropdownMenuItem>
                    )}
                    {hasTrace && (
                      <DropdownMenuItem
                        disabled={traceLaunchingRunId === c.latest_run!.id}
                        onClick={() => onViewTrace(c.latest_run!.id)}
                      >
                        {traceLaunchingRunId === c.latest_run!.id ? (
                          <Loader2 className="size-3.5 animate-spin" />
                        ) : (
                          <Film className="size-3.5" />
                        )}
                        {t(($) => $.test_cases.view_trace)}
                      </DropdownMenuItem>
                    )}
                    {canFileBug && (
                      <DropdownMenuItem onClick={onFileBug}>
                        <Bug className="size-3.5 text-destructive" />
                        {t(($) => $.test_cases.file_bug_case)}
                      </DropdownMenuItem>
                    )}
                  </DropdownMenuContent>
                </DropdownMenu>
              )}
            </>
          )}
        </div>
      </div>
      {stepRunOpen && (
        <StepRunChecklist
          steps={parsedSteps}
          busy={busy}
          onCancel={() => setStepRunOpen(false)}
          onFinish={(verdict, output) => {
            onStepRun(verdict, output);
            setStepRunOpen(false);
          }}
        />
      )}
      {/* Case taxonomy — priority · flaky · modality · criterion · kind ·
          category · (who ran it + when). Hidden on the collapsed row; the
          reviewer only needs it once they open a specific case. */}
      {open && (
        <div className="mt-1.5 flex flex-wrap items-center gap-x-1 gap-y-0.5 pl-1 text-[10px] text-muted-foreground/70">
          <span className={cn("uppercase", priorityChipClass(c.priority))}>{priorityLabel(c.priority)}</span>
          {c.flaky === true && (
            <>
              <span aria-hidden>·</span>
              {/* Flaky: pass AND fail on the SAME commit — same amber caution. */}
              <span
                className="font-medium uppercase text-amber-600 dark:text-amber-400"
                title={t(($) => $.test_cases.flaky_title)}
              >
                {t(($) => $.test_cases.flaky)}
              </span>
            </>
          )}
          {c.modality && (
            <>
              <span aria-hidden>·</span>
              <span>{modalityLabel(c.modality)}</span>
            </>
          )}
          {c.criterion_ref && (
            <>
              <span aria-hidden>·</span>
              <span className="max-w-[140px] truncate" title={c.criterion_ref}>
                {c.criterion_ref}
              </span>
            </>
          )}
          <span aria-hidden>·</span>
          <span>{kindLabel}</span>
          <span aria-hidden>·</span>
          <span className={cn(c.category === "negative" && "font-medium text-amber-600 dark:text-amber-400")}>
            {categoryLabel}
          </span>
          {c.latest_run && (
            <>
              <span aria-hidden>·</span>
              {c.latest_run.run_source === "agent" ? (
                <Bot className="size-2.5 shrink-0" />
              ) : (
                <User className="size-2.5 shrink-0" />
              )}
              {timeAgo(c.latest_run.created_at)}
            </>
          )}
        </div>
      )}
      {open && hasReason && (
        <div
          className={cn(
            "mt-1.5 rounded border-l-2 px-2 py-1.5 text-[11px]",
            status === "fail"
              ? "border-destructive/50 bg-destructive/5 text-destructive/90"
              : "border-amber-500/50 bg-amber-500/5 text-amber-700 dark:text-amber-400",
          )}
        >
          {/* A checklist walk renders as a structured per-step breakdown;
              an agent's free-text evidence keeps the raw <pre>. */}
          {stepResults ? (
            <StepResultList results={stepResults} steps={parsedSteps} />
          ) : (
            <pre className="whitespace-pre-wrap break-words font-mono">{c.latest_run?.output}</pre>
          )}
        </div>
      )}
      {/* A PASSING checklist walk has no tinted reason block — still surface
          its per-step breakdown in the expanded detail. */}
      {open && !hasReason && stepResults && (
        <div className="mt-1.5 rounded border-l-2 border-border bg-muted/20 px-2 py-1.5 text-[11px] text-muted-foreground">
          <StepResultList results={stepResults} steps={parsedSteps} />
        </div>
      )}
      {/* Run history strip (Phase 3): the last 5 runs as verdict dots, with
          time + source + short sha in the tooltip — "is this case settling
          or churning" at a glance. Renders only when history exists. */}
      {open && historyRuns.length > 0 && (
        <div className="mt-1.5 flex items-center gap-1.5 pl-1 text-[10px] text-muted-foreground">
          <span>{t(($) => $.test_cases.run_history)}:</span>
          <span className="flex items-center gap-1">
            {historyRuns.map((r) => (
              <span
                key={r.id}
                aria-hidden={false}
                title={`${r.status} · ${r.run_source}${r.commit_sha ? ` · ${r.commit_sha.slice(0, 7)}` : ""}${r.created_at ? ` · ${new Date(r.created_at).toLocaleString()}` : ""}`}
                className={cn(
                  "size-2 rounded-full",
                  r.status === "pass"
                    ? "bg-emerald-500"
                    : r.status === "fail"
                      ? "bg-destructive"
                      : "bg-muted-foreground/40",
                )}
              />
            ))}
          </span>
        </div>
      )}
      {open && (c.steps || c.expected || c.preconditions) && (
        <div className="mt-1.5 space-y-1 pl-1 text-[12px] text-muted-foreground">
          {c.preconditions && (
            <p>
              <span className="text-foreground/70">{t(($) => $.test_cases.preconditions_label)}: </span>
              {c.preconditions}
            </p>
          )}
          {c.steps && <StepList text={c.steps} />}
          {c.expected && (
            <p>
              <span className="text-foreground/70">→ </span>
              {c.expected}
            </p>
          )}
        </div>
      )}
    </li>
  );
}

function AddCaseForm({ issueId, onDone }: { issueId: string; onDone: () => void }) {
  const { t } = useT("issues");
  const [title, setTitle] = useState("");
  const [preconditions, setPreconditions] = useState("");
  const [steps, setSteps] = useState<ParsedStep[]>([{ action: "", expects: "" }]);
  const [expected, setExpected] = useState("");
  const [kind, setKind] = useState<"manual" | "automated">("manual");
  const [category, setCategory] = useState<"positive" | "negative">("positive");
  const [priority, setPriority] = useState<TestCasePriority>("p2");
  const [modality, setModality] = useState<TestCaseModality>("");
  const [criterionRef, setCriterionRef] = useState("");

  // Picking a template REPLACES the whole draft — it's a starting point the
  // author then edits, not a merge into half-typed fields.
  const applyTemplate = (tpl: CaseTemplate) => {
    setTitle(tpl.title);
    setPreconditions(tpl.preconditions);
    setSteps(tpl.steps.map((s) => ({ ...s })));
    setExpected(tpl.expected);
    setKind(tpl.kind);
    setCategory(tpl.category);
    setPriority(tpl.priority);
    setModality(tpl.modality);
  };
  const templateLabel = (id: CaseTemplate["id"]): string => {
    switch (id) {
      case "login_flow":
        return t(($) => $.test_cases.template_login_flow);
      case "crud_happy_path":
        return t(($) => $.test_cases.template_crud_happy_path);
      case "negative_validation":
        return t(($) => $.test_cases.template_negative_validation);
      case "api_contract":
        return t(($) => $.test_cases.template_api_contract);
    }
  };

  const save = useMutation({
    mutationFn: () =>
      api.createIssueTestCase(issueId, {
        title: title.trim(),
        steps: serializeSteps(steps.filter((s) => s.action.trim() !== "")),
        expected,
        kind,
        category,
        preconditions,
        priority,
        modality,
        criterion_ref: criterionRef.trim(),
      }),
    onSuccess: onDone,
    onError: (e) => toast.error(e instanceof Error ? e.message : "Failed"),
  });

  return (
    <div className="space-y-2 rounded-lg border bg-muted/20 p-3">
      <DropdownMenu>
        <DropdownMenuTrigger
          render={
            <Button type="button" variant="outline" size="sm" className="h-6 px-2 text-[11px] text-muted-foreground">
              {t(($) => $.test_cases.template_picker)}
            </Button>
          }
        />
        <DropdownMenuContent align="start">
          {CASE_TEMPLATES.map((tpl) => (
            <DropdownMenuItem key={tpl.id} onClick={() => applyTemplate(tpl)} className="text-[12px]">
              {templateLabel(tpl.id)}
            </DropdownMenuItem>
          ))}
        </DropdownMenuContent>
      </DropdownMenu>
      <Input
        placeholder={t(($) => $.test_cases.title_ph)}
        value={title}
        onChange={(e) => setTitle(e.target.value)}
        className="h-8 text-[13px]"
      />
      <Textarea
        placeholder={t(($) => $.test_cases.preconditions_ph)}
        value={preconditions}
        onChange={(e) => setPreconditions(e.target.value)}
        rows={1}
        className="text-[12px]"
      />
      <StepEditor steps={steps} onChange={setSteps} />
      <Textarea
        placeholder={t(($) => $.test_cases.expected_ph)}
        value={expected}
        onChange={(e) => setExpected(e.target.value)}
        rows={1}
        className="text-[12px]"
      />
      {/* Traceability (optional): which acceptance criterion this case covers. */}
      <Input
        placeholder={t(($) => $.test_cases.criterion_ref_ph)}
        value={criterionRef}
        onChange={(e) => setCriterionRef(e.target.value)}
        className="h-7 text-[12px]"
      />
      {/* Two toggle groups stack on their own rows in a narrow rail — forcing
          both onto one row with the Save button is what overflowed before. */}
      <div className="flex flex-wrap items-center gap-1.5">
        <div className="flex rounded-md border p-0.5">
          {(["manual", "automated"] as const).map((k) => (
            <Button
              key={k}
              type="button"
              variant="ghost"
              size="sm"
              onClick={() => setKind(k)}
              className={cn(
                "h-6 px-2 text-[11px]",
                kind === k ? "bg-muted font-medium text-foreground" : "text-muted-foreground",
              )}
            >
              {k === "manual" ? t(($) => $.test_cases.kind_manual) : t(($) => $.test_cases.kind_automated)}
            </Button>
          ))}
        </div>
        <div className="flex rounded-md border p-0.5">
          {(["positive", "negative"] as const).map((cat) => (
            <Button
              key={cat}
              type="button"
              variant="ghost"
              size="sm"
              onClick={() => setCategory(cat)}
              className={cn(
                "h-6 px-2 text-[11px]",
                category === cat ? "bg-muted font-medium text-foreground" : "text-muted-foreground",
              )}
            >
              {cat === "positive" ? t(($) => $.test_cases.category_positive) : t(($) => $.test_cases.category_negative)}
            </Button>
          ))}
        </div>
        <PriorityToggle value={priority} onChange={setPriority} />
        <ModalityToggle value={modality} onChange={setModality} />
      </div>
      <Button
        type="button"
        size="sm"
        className="w-full h-7 text-[12px]"
        disabled={!title.trim() || save.isPending}
        onClick={() => save.mutate()}
      >
        {save.isPending ? <Loader2 className="size-3.5 animate-spin" /> : t(($) => $.test_cases.save)}
      </Button>
    </div>
  );
}
