"use client";

import { useState } from "react";
import { useQuery, useQueryClient, useMutation } from "@tanstack/react-query";
import { Sparkles, Plus, Bot, User, Loader2, FlaskConical, Play, CircleSlash, Check, X, Film } from "lucide-react";
import { toast } from "sonner";
import { api } from "@agora/core/api";
import { issueKeys, testCasesOptions } from "@agora/core/issues/queries";
import type { TestCase } from "@agora/core/types";
import { Button } from "@agora/ui/components/ui/button";
import { Input } from "@agora/ui/components/ui/input";
import { Textarea } from "@agora/ui/components/ui/textarea";
import { cn } from "@agora/ui/lib/utils";
import { useT, useTimeAgo } from "../../i18n";
import { useRunningTestCaseId, useLiveCaseVerdicts } from "./qa-live-progress";
import { verdictIcon } from "./verdict";

// The QA team's Test-cases instrument. Lists an issue's cases (authored by a QA
// human OR generated by a QA-Squad agent via gen_test_cases), each with its
// latest run verdict, and lets QA add cases, generate via agent, and record a
// pass/fail run. Automated execution + regression are later phases.
//
// Density note: this panel lives in a fixed 400px rail (see qa-review-page),
// same width class as the issue detail page's Properties panel — every
// control here is icon-first / single-line-per-row on purpose, not a
// scaled-down version of a wide layout. Badges became plain muted text,
// header actions became icon buttons with tooltips, and Pass/Fail became
// small icon buttons instead of text pills, all to fit without truncating
// or wrapping into a 3-line mess.

export function TestCasesPanel({ issueId }: { issueId: string }) {
  const { t } = useT("issues");
  const qc = useQueryClient();
  const { data } = useQuery(testCasesOptions(issueId));
  const cases = data?.test_cases ?? [];
  const [adding, setAdding] = useState(false);
  // The Playwright trace viewer opens as a full-panel overlay iframe — the URL
  // is a same-origin reverse-proxy path the backend hands back per launch.
  const [traceUrl, setTraceUrl] = useState<string | null>(null);
  const runningCaseId = useRunningTestCaseId(issueId);
  const liveVerdicts = useLiveCaseVerdicts(issueId);

  const invalidate = () => qc.invalidateQueries({ queryKey: issueKeys.testCases(issueId) });

  const generate = useMutation({
    mutationFn: () => api.generateTestCases(issueId),
    onSuccess: () => {
      toast.success(t(($) => $.test_cases.generated_toast));
      invalidate();
    },
    onError: (e) => toast.error(e instanceof Error ? e.message : "Failed"),
  });

  const runAll = useMutation({
    mutationFn: () => api.runTestCases(issueId),
    onSuccess: () => {
      toast.success(t(($) => $.test_cases.run_all_toast));
      invalidate();
    },
    onError: (e) => toast.error(e instanceof Error ? e.message : "Failed"),
  });

  const hasAutomated = cases.some((c) => c.kind === "automated");
  // Coverage at a glance: a senior QA reviewer's first question is "do we have
  // both?" — a case pile that's all positive has no evidence anything fails
  // safely. Counted here once so the header doesn't scan the list twice.
  const negativeCount = cases.filter((c) => c.category === "negative").length;
  const positiveCount = cases.length - negativeCount;

  const recordRun = useMutation({
    mutationFn: ({ caseId, status }: { caseId: string; status: "pass" | "fail" }) =>
      api.recordTestCaseRun(caseId, { status }),
    onSuccess: invalidate,
    onError: (e) => toast.error(e instanceof Error ? e.message : "Failed"),
  });

  const launchTrace = useMutation({
    mutationFn: (runId: string) => api.launchTrace(runId),
    onSuccess: (res) => {
      if (res.trace_url) setTraceUrl(res.trace_url);
      else toast.error(t(($) => $.test_cases.trace_error));
    },
    onError: (e) => toast.error(e instanceof Error ? e.message : t(($) => $.test_cases.trace_error)),
  });

  return (
    <section className="space-y-2">
      <div className="flex items-center gap-2">
        <FlaskConical className="size-4 shrink-0 text-muted-foreground" />
        <span className="text-sm font-medium">{t(($) => $.test_cases.section)}</span>
        <span className="rounded bg-muted px-1.5 py-0.5 text-[11px] text-muted-foreground">{cases.length}</span>
        <div className="ml-auto flex items-center gap-1">
          {hasAutomated && (
            <Button
              type="button"
              size="icon"
              variant="outline"
              className="size-7"
              disabled={runAll.isPending}
              onClick={() => runAll.mutate()}
              title={runAll.isPending ? t(($) => $.test_cases.running_all) : t(($) => $.test_cases.run_all)}
            >
              {runAll.isPending ? <Loader2 className="size-3.5 animate-spin" /> : <Play className="size-3.5" />}
            </Button>
          )}
          <Button
            type="button"
            size="icon"
            variant="outline"
            className="size-7"
            disabled={generate.isPending}
            onClick={() => generate.mutate()}
            title={generate.isPending ? t(($) => $.test_cases.generating) : t(($) => $.test_cases.generate)}
          >
            {generate.isPending ? <Loader2 className="size-3.5 animate-spin" /> : <Sparkles className="size-3.5" />}
          </Button>
          <Button
            type="button"
            size="icon"
            variant="outline"
            className="size-7"
            onClick={() => setAdding((v) => !v)}
            title={t(($) => $.test_cases.add)}
          >
            <Plus className="size-3.5" />
          </Button>
        </div>
      </div>

      {/* Coverage summary on its own line — the header row above is already
          tight with the icon buttons; forcing this onto the same line is
          what caused the wrap/overflow. */}
      {cases.length > 0 && (
        <div className="flex items-center gap-1 text-[11px] text-muted-foreground">
          <span>
            {positiveCount} {t(($) => $.test_cases.category_positive)}
          </span>
          <span aria-hidden>·</span>
          <span
            className={cn(negativeCount === 0 && "font-medium text-amber-600 dark:text-amber-400")}
            title={negativeCount === 0 ? t(($) => $.test_cases.category_negative_missing_hint) : undefined}
          >
            {negativeCount} {t(($) => $.test_cases.category_negative)}
          </span>
        </div>
      )}

      {adding && <AddCaseForm issueId={issueId} onDone={() => { setAdding(false); invalidate(); }} />}

      {cases.length === 0 && !adding ? (
        <div className="rounded-lg border border-dashed bg-muted/20 px-3 py-5 text-center">
          <p className="text-[12px] text-muted-foreground">{t(($) => $.test_cases.empty)}</p>
          <p className="mt-0.5 text-[11px] text-muted-foreground/70">{t(($) => $.test_cases.empty_hint)}</p>
        </div>
      ) : (
        <ul className="divide-y rounded-lg border">
          {cases.map((c) => (
            <CaseRow
              key={c.id}
              c={c}
              busy={recordRun.isPending}
              onRun={(status) => recordRun.mutate({ caseId: c.id, status })}
              isRunning={c.id === runningCaseId}
              liveVerdict={liveVerdicts[c.id]}
              onViewTrace={(runId) => launchTrace.mutate(runId)}
              traceLaunchingRunId={launchTrace.isPending ? launchTrace.variables ?? null : null}
            />
          ))}
        </ul>
      )}

      {traceUrl && <TraceOverlay url={traceUrl} onClose={() => setTraceUrl(null)} />}
    </section>
  );
}

// Full-panel overlay hosting the real Playwright trace viewer in an iframe. The
// src is a same-origin reverse-proxy URL (behind the authed session), so the
// viewer + its DOM snapshots / screenshots stream through the backend — no
// vendored viewer, no cross-origin auth wall. Esc / the close button dismiss it.
function TraceOverlay({ url, onClose }: { url: string; onClose: () => void }) {
  const { t } = useT("issues");
  return (
    <div className="fixed inset-0 z-50 flex flex-col bg-background">
      <div className="flex items-center gap-2 border-b px-3 py-2">
        <Film className="size-4 shrink-0 text-muted-foreground" />
        <span className="text-sm font-medium">{t(($) => $.test_cases.trace_title)}</span>
        <Button
          type="button"
          variant="ghost"
          size="icon"
          className="ml-auto size-7"
          onClick={onClose}
          title={t(($) => $.test_cases.trace_close)}
        >
          <X className="size-4" />
        </Button>
      </div>
      <iframe
        src={url}
        title={t(($) => $.test_cases.trace_title)}
        className="min-h-0 flex-1 border-0"
      />
    </div>
  );
}

function CaseRow({
  c,
  busy,
  onRun,
  isRunning,
  liveVerdict,
  onViewTrace,
  traceLaunchingRunId,
}: {
  c: TestCase;
  busy: boolean;
  onRun: (status: "pass" | "fail") => void;
  // Open the Playwright trace viewer for this case's latest run (only wired when
  // that run captured a trace). The panel owns the overlay; the row just fires.
  onViewTrace: (runId: string) => void;
  // The run id whose trace launch is in flight (shows a spinner on that button),
  // or null. Panel-level so a second row's button isn't disabled by this one.
  traceLaunchingRunId: string | null;
  // Jest-style "RUNS <spec>" — true while the live agent stream's most recent
  // `RUNNING test_case:<id>` marker (see useRunningTestCaseId) names THIS case.
  // Takes priority over the persisted latest_run status, which is correct: a
  // case being re-run right now should show as running, not as its stale
  // previous verdict.
  isRunning: boolean;
  // Live verdict parsed from the running stream's `QA_RESULT test_case:<id>`
  // marker — the case just finished THIS run but its test_run row hasn't
  // persisted yet. Shown as ✓/✗ with a "live" pulse so the panel updates in
  // real time; superseded by the persisted status once the run ends.
  liveVerdict?: "pass" | "fail";
}) {
  const { t } = useT("issues");
  const timeAgo = useTimeAgo();
  // Precedence: running now > this run's just-finished live verdict > persisted.
  const status = isRunning ? undefined : liveVerdict ?? c.latest_run?.status;
  const isLive = !isRunning && !!liveVerdict && liveVerdict === status && !c.latest_run;
  // "blocked"/"skip" only ever comes from the agent's run_test_cases protocol
  // (the human Pass/Fail buttons only ever write pass/fail) — it means the
  // agent attempted this case and could NOT exercise it (no reachable
  // browser, missing data/route), which reads very differently from "never
  // attempted" (no latest_run at all). c.latest_run?.output carries the
  // agent's one-line reason.
  const isBlocked = status === "blocked" || status === "skip";
  const hasReason = !isRunning && (status === "fail" || isBlocked) && !!c.latest_run?.output;
  // Jest-style: a failing/blocked case opens itself so the reason is visible
  // without an extra click — the whole point of asking "which failed and why"
  // is to NOT have to hunt for it. A passing/never-run case stays collapsed.
  const [open, setOpen] = useState(hasReason);
  const kindLabel = c.kind === "automated" ? t(($) => $.test_cases.kind_automated) : t(($) => $.test_cases.kind_manual);
  const categoryLabel =
    c.category === "negative" ? t(($) => $.test_cases.category_negative) : t(($) => $.test_cases.category_positive);

  return (
    <li
      className={cn(
        "px-3 py-2 transition-colors",
        // The case executing RIGHT NOW is unmistakable: tinted row + a left
        // accent bar + a spinning marker on the title (below). Jest-runner feel.
        isRunning && "border-l-2 border-info bg-info/5",
      )}
    >
      <div className="flex items-start gap-2">
        <button type="button" className="min-w-0 flex-1 text-left" onClick={() => setOpen((v) => !v)}>
          <span
            className={cn(
              "flex items-center gap-1.5 truncate text-[13px]",
              isRunning && "font-medium text-info",
            )}
          >
            {isRunning && <Loader2 className="size-3 shrink-0 animate-spin" aria-hidden />}
            <span className="truncate">{c.title}</span>
          </span>
          {/* Compact meta: kind · category · (who ran it + when) — plain text,
              not badge pills, so it fits a 400px rail on one wrapping-safe line. */}
          <span className="mt-0.5 flex flex-wrap items-center gap-x-1 gap-y-0.5 text-[10px] text-muted-foreground/70">
            <span>{kindLabel}</span>
            <span aria-hidden>·</span>
            <span
              className={cn(c.category === "negative" && "font-medium text-amber-600 dark:text-amber-400")}
            >
              {categoryLabel}
            </span>
            {!isRunning && c.latest_run && (
              <>
                <span aria-hidden>·</span>
                {c.latest_run.run_source === "agent" ? (
                  <Bot className="size-2.5 shrink-0" />
                ) : (
                  <User className="size-2.5 shrink-0" />
                )}
                {timeAgo(c.latest_run.created_at)}
              </>
            )}
          </span>
        </button>
        <div className="flex shrink-0 items-center gap-1.5 pt-0.5">
          {isRunning ? (
            <span className="flex items-center gap-1 text-[10px] font-medium text-info">
              <span aria-hidden className="size-1.5 shrink-0 rounded-full bg-info motion-safe:animate-pulse" />
              {t(($) => $.test_cases.runs_now)}
            </span>
          ) : status === "pass" || status === "fail" ? (
            <span
              className={cn(isLive && "motion-safe:animate-pulse")}
              title={
                isLive
                  ? t(($) => $.test_cases.runs_now)
                  : status === "fail"
                    ? c.latest_run?.output || undefined
                    : undefined
              }
            >
              {verdictIcon(status, "size-4")}
            </span>
          ) : isBlocked ? (
            <span title={c.latest_run?.output || t(($) => $.test_cases.blocked)}>
              <CircleSlash className="size-4 text-amber-600 dark:text-amber-400" />
            </span>
          ) : (
            <span className="text-[10px] text-muted-foreground">—</span>
          )}
          {c.latest_run?.trace_path && c.latest_run.id && (
            <Button
              type="button"
              variant="ghost"
              size="icon"
              disabled={traceLaunchingRunId === c.latest_run.id}
              onClick={() => onViewTrace(c.latest_run!.id)}
              className="size-6 text-info hover:bg-info/10"
              title={t(($) => $.test_cases.view_trace)}
            >
              {traceLaunchingRunId === c.latest_run.id ? (
                <Loader2 className="size-3.5 animate-spin" />
              ) : (
                <Film className="size-3.5" />
              )}
            </Button>
          )}
          <Button
            type="button"
            variant="ghost"
            size="icon"
            disabled={busy}
            onClick={() => onRun("pass")}
            className="size-6 text-emerald-700 hover:bg-emerald-600/10 dark:text-emerald-300"
            title={t(($) => $.test_cases.run_pass)}
          >
            <Check className="size-3.5" />
          </Button>
          <Button
            type="button"
            variant="ghost"
            size="icon"
            disabled={busy}
            onClick={() => onRun("fail")}
            className="size-6 text-destructive hover:bg-destructive/10"
            title={t(($) => $.test_cases.run_fail)}
          >
            <X className="size-3.5" />
          </Button>
        </div>
      </div>
      {open && hasReason && (
        <div
          className={cn(
            "mt-1.5 rounded border-l-2 px-2 py-1.5 text-[11px]",
            status === "fail"
              ? "border-destructive/50 bg-destructive/5 text-destructive/90"
              : "border-amber-500/50 bg-amber-500/5 text-amber-700 dark:text-amber-400",
          )}
        >
          <pre className="whitespace-pre-wrap break-words font-mono">{c.latest_run?.output}</pre>
        </div>
      )}
      {open && (c.steps || c.expected) && (
        <div className="mt-1.5 space-y-1 pl-1 text-[12px] text-muted-foreground">
          {c.steps && <pre className="whitespace-pre-wrap font-sans">{c.steps}</pre>}
          {c.expected && (
            <p>
              <span className="text-foreground/70">→ </span>
              {c.expected}
            </p>
          )}
        </div>
      )}
    </li>
  );
}

function AddCaseForm({ issueId, onDone }: { issueId: string; onDone: () => void }) {
  const { t } = useT("issues");
  const [title, setTitle] = useState("");
  const [steps, setSteps] = useState("");
  const [expected, setExpected] = useState("");
  const [kind, setKind] = useState<"manual" | "automated">("manual");
  const [category, setCategory] = useState<"positive" | "negative">("positive");

  const save = useMutation({
    mutationFn: () => api.createIssueTestCase(issueId, { title: title.trim(), steps, expected, kind, category }),
    onSuccess: onDone,
    onError: (e) => toast.error(e instanceof Error ? e.message : "Failed"),
  });

  return (
    <div className="space-y-2 rounded-lg border bg-muted/20 p-3">
      <Input
        placeholder={t(($) => $.test_cases.title_ph)}
        value={title}
        onChange={(e) => setTitle(e.target.value)}
        className="h-8 text-[13px]"
      />
      <Textarea
        placeholder={t(($) => $.test_cases.steps_ph)}
        value={steps}
        onChange={(e) => setSteps(e.target.value)}
        rows={2}
        className="text-[12px]"
      />
      <Textarea
        placeholder={t(($) => $.test_cases.expected_ph)}
        value={expected}
        onChange={(e) => setExpected(e.target.value)}
        rows={1}
        className="text-[12px]"
      />
      {/* Two toggle groups stack on their own rows in a narrow rail — forcing
          both onto one row with the Save button is what overflowed before. */}
      <div className="flex flex-wrap items-center gap-1.5">
        <div className="flex rounded-md border p-0.5">
          {(["manual", "automated"] as const).map((k) => (
            <Button
              key={k}
              type="button"
              variant="ghost"
              size="sm"
              onClick={() => setKind(k)}
              className={cn(
                "h-6 px-2 text-[11px]",
                kind === k ? "bg-muted font-medium text-foreground" : "text-muted-foreground",
              )}
            >
              {k === "manual" ? t(($) => $.test_cases.kind_manual) : t(($) => $.test_cases.kind_automated)}
            </Button>
          ))}
        </div>
        <div className="flex rounded-md border p-0.5">
          {(["positive", "negative"] as const).map((cat) => (
            <Button
              key={cat}
              type="button"
              variant="ghost"
              size="sm"
              onClick={() => setCategory(cat)}
              className={cn(
                "h-6 px-2 text-[11px]",
                category === cat ? "bg-muted font-medium text-foreground" : "text-muted-foreground",
              )}
            >
              {cat === "positive" ? t(($) => $.test_cases.category_positive) : t(($) => $.test_cases.category_negative)}
            </Button>
          ))}
        </div>
      </div>
      <Button
        type="button"
        size="sm"
        className="w-full h-7 text-[12px]"
        disabled={!title.trim() || save.isPending}
        onClick={() => save.mutate()}
      >
        {save.isPending ? <Loader2 className="size-3.5 animate-spin" /> : t(($) => $.test_cases.save)}
      </Button>
    </div>
  );
}
