"use client";

import { useState } from "react";
import { useQuery, useQueryClient, useMutation } from "@tanstack/react-query";
import { Sparkles, Plus, CheckCircle2, XCircle, Bot, User, Loader2, FlaskConical } from "lucide-react";
import { toast } from "sonner";
import { api } from "@agora/core/api";
import { issueKeys, testCasesOptions } from "@agora/core/issues/queries";
import type { TestCase } from "@agora/core/types";
import { Button } from "@agora/ui/components/ui/button";
import { Input } from "@agora/ui/components/ui/input";
import { cn } from "@agora/ui/lib/utils";
import { useT } from "../../i18n";

// The QA team's Test-cases instrument. Lists an issue's cases (authored by a QA
// human OR generated by a QA-Squad agent via gen_test_cases), each with its
// latest run verdict, and lets QA add cases, generate via agent, and record a
// pass/fail run. Automated execution + regression are later phases.

export function TestCasesPanel({ issueId }: { issueId: string }) {
  const { t } = useT("issues");
  const qc = useQueryClient();
  const { data } = useQuery(testCasesOptions(issueId));
  const cases = data?.test_cases ?? [];
  const [adding, setAdding] = useState(false);

  const invalidate = () => qc.invalidateQueries({ queryKey: issueKeys.testCases(issueId) });

  const generate = useMutation({
    mutationFn: () => api.generateTestCases(issueId),
    onSuccess: () => toast.success(t(($) => $.test_cases.generated_toast)),
    onError: (e) => toast.error(e instanceof Error ? e.message : "Failed"),
  });

  const recordRun = useMutation({
    mutationFn: ({ caseId, status }: { caseId: string; status: "pass" | "fail" }) =>
      api.recordTestCaseRun(caseId, { status }),
    onSuccess: invalidate,
    onError: (e) => toast.error(e instanceof Error ? e.message : "Failed"),
  });

  return (
    <section className="space-y-2">
      <div className="flex items-center gap-2">
        <FlaskConical className="size-4 text-muted-foreground" />
        <span className="text-sm font-medium">{t(($) => $.test_cases.section)}</span>
        <span className="rounded bg-muted px-1.5 py-0.5 text-[11px] text-muted-foreground">{cases.length}</span>
        <div className="ml-auto flex items-center gap-1.5">
          <Button
            type="button"
            size="sm"
            variant="outline"
            className="h-7 gap-1.5 text-[12px]"
            disabled={generate.isPending}
            onClick={() => generate.mutate()}
          >
            {generate.isPending ? <Loader2 className="size-3.5 animate-spin" /> : <Sparkles className="size-3.5" />}
            {generate.isPending ? t(($) => $.test_cases.generating) : t(($) => $.test_cases.generate)}
          </Button>
          <Button
            type="button"
            size="sm"
            variant="outline"
            className="h-7 gap-1.5 text-[12px]"
            onClick={() => setAdding((v) => !v)}
          >
            <Plus className="size-3.5" />
            {t(($) => $.test_cases.add)}
          </Button>
        </div>
      </div>

      {adding && <AddCaseForm issueId={issueId} onDone={() => { setAdding(false); invalidate(); }} />}

      {cases.length === 0 && !adding ? (
        <div className="rounded-lg border border-dashed bg-muted/20 px-3 py-5 text-center">
          <p className="text-[12px] text-muted-foreground">{t(($) => $.test_cases.empty)}</p>
          <p className="mt-0.5 text-[11px] text-muted-foreground/70">{t(($) => $.test_cases.empty_hint)}</p>
        </div>
      ) : (
        <ul className="divide-y rounded-lg border">
          {cases.map((c) => (
            <CaseRow
              key={c.id}
              c={c}
              busy={recordRun.isPending}
              onRun={(status) => recordRun.mutate({ caseId: c.id, status })}
            />
          ))}
        </ul>
      )}
    </section>
  );
}

function CaseRow({
  c,
  busy,
  onRun,
}: {
  c: TestCase;
  busy: boolean;
  onRun: (status: "pass" | "fail") => void;
}) {
  const { t } = useT("issues");
  const [open, setOpen] = useState(false);
  const status = c.latest_run?.status;
  return (
    <li className="px-3 py-2">
      <div className="flex items-center gap-2">
        <button type="button" className="min-w-0 flex-1 text-left" onClick={() => setOpen((v) => !v)}>
          <span className="truncate text-[13px]">{c.title}</span>
        </button>
        <span className="flex items-center gap-1 rounded bg-muted px-1.5 py-0.5 text-[10px] text-muted-foreground">
          {c.source === "agent" ? <Bot className="size-3" /> : <User className="size-3" />}
          {c.source === "agent" ? t(($) => $.test_cases.src_agent) : t(($) => $.test_cases.src_human)}
        </span>
        <span className="rounded border px-1.5 py-0.5 text-[10px] text-muted-foreground">
          {c.kind === "automated" ? t(($) => $.test_cases.kind_automated) : t(($) => $.test_cases.kind_manual)}
        </span>
        {status === "pass" ? (
          <CheckCircle2 className="size-4 text-emerald-600 dark:text-emerald-400" />
        ) : status === "fail" ? (
          <XCircle className="size-4 text-destructive" />
        ) : (
          <span className="text-[10px] text-muted-foreground">—</span>
        )}
        <div className="flex items-center gap-1">
          <button
            type="button"
            disabled={busy}
            onClick={() => onRun("pass")}
            className="rounded px-1.5 py-0.5 text-[11px] text-emerald-700 hover:bg-emerald-600/10 dark:text-emerald-300"
          >
            {t(($) => $.test_cases.run_pass)}
          </button>
          <button
            type="button"
            disabled={busy}
            onClick={() => onRun("fail")}
            className="rounded px-1.5 py-0.5 text-[11px] text-destructive hover:bg-destructive/10"
          >
            {t(($) => $.test_cases.run_fail)}
          </button>
        </div>
      </div>
      {open && (c.steps || c.expected) && (
        <div className="mt-1.5 space-y-1 pl-1 text-[12px] text-muted-foreground">
          {c.steps && <pre className="whitespace-pre-wrap font-sans">{c.steps}</pre>}
          {c.expected && (
            <p>
              <span className="text-foreground/70">→ </span>
              {c.expected}
            </p>
          )}
        </div>
      )}
    </li>
  );
}

function AddCaseForm({ issueId, onDone }: { issueId: string; onDone: () => void }) {
  const { t } = useT("issues");
  const [title, setTitle] = useState("");
  const [steps, setSteps] = useState("");
  const [expected, setExpected] = useState("");
  const [kind, setKind] = useState<"manual" | "automated">("manual");

  const save = useMutation({
    mutationFn: () => api.createIssueTestCase(issueId, { title: title.trim(), steps, expected, kind }),
    onSuccess: onDone,
    onError: (e) => toast.error(e instanceof Error ? e.message : "Failed"),
  });

  return (
    <div className="space-y-2 rounded-lg border bg-muted/20 p-3">
      <Input
        placeholder={t(($) => $.test_cases.title_ph)}
        value={title}
        onChange={(e) => setTitle(e.target.value)}
        className="h-8 text-[13px]"
      />
      <textarea
        placeholder={t(($) => $.test_cases.steps_ph)}
        value={steps}
        onChange={(e) => setSteps(e.target.value)}
        rows={2}
        className="w-full rounded-md border bg-background px-2 py-1.5 text-[12px]"
      />
      <textarea
        placeholder={t(($) => $.test_cases.expected_ph)}
        value={expected}
        onChange={(e) => setExpected(e.target.value)}
        rows={1}
        className="w-full rounded-md border bg-background px-2 py-1.5 text-[12px]"
      />
      <div className="flex items-center gap-2">
        <div className="flex rounded-md border p-0.5">
          {(["manual", "automated"] as const).map((k) => (
            <button
              key={k}
              type="button"
              onClick={() => setKind(k)}
              className={cn(
                "rounded px-2 py-0.5 text-[11px]",
                kind === k ? "bg-muted font-medium text-foreground" : "text-muted-foreground",
              )}
            >
              {k === "manual" ? t(($) => $.test_cases.kind_manual) : t(($) => $.test_cases.kind_automated)}
            </button>
          ))}
        </div>
        <Button
          type="button"
          size="sm"
          className="ml-auto h-7 text-[12px]"
          disabled={!title.trim() || save.isPending}
          onClick={() => save.mutate()}
        >
          {save.isPending ? <Loader2 className="size-3.5 animate-spin" /> : t(($) => $.test_cases.save)}
        </Button>
      </div>
    </div>
  );
}
