package handler

import (
	"context"
	"encoding/json"
	"net/http"
	"strings"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/jackc/pgx/v5/pgtype"
	db "github.com/multica-ai/multica/server/pkg/db/generated"
	"github.com/multica-ai/multica/server/pkg/protocol"
)

// QA test cases — the QA team's test-management instruments. A case is authored
// by a QA human (this API) or generated by a QA-Squad agent (the gen_test_cases
// slice action, captured server-side). A run records one execution's verdict.

type TestRunLite struct {
	// ID is the test_run row id — the handle the trace-viewer launch endpoint
	// (GET /api/qa/trace/:runId) takes. Sent so the panel can request a trace for
	// exactly this run without a second lookup.
	ID        string `json:"id"`
	Status    string `json:"status"`
	RunSource string `json:"run_source"`
	CreatedAt string `json:"created_at"`
	// Output is the one-line evidence an agent reports per case (e.g. "embedded
	// browser unreachable") via the run_test_cases test-runs protocol. Surfaced
	// so a "blocked" verdict tells QA WHY, not just that it didn't run.
	Output string `json:"output,omitempty"`
	// TracePath is non-empty when this run captured a Playwright trace on the
	// agent's runtime box. The panel gates its "View trace" affordance on it;
	// the raw path never leaves the backend for anything but the launch call.
	TracePath string `json:"trace_path,omitempty"`
}

type TestCaseResponse struct {
	ID         string `json:"id"`
	IssueID    string `json:"issue_id"`
	Title      string `json:"title"`
	Steps      string `json:"steps"`
	Expected   string `json:"expected"`
	Kind       string `json:"kind"`
	Source     string `json:"source"`
	AuthorType string `json:"author_type"`
	Category   string `json:"category"` // positive | negative
	// Script is the compiled Playwright script for an automated case, if any.
	// Empty means the case is hand-driven (no compiled runner) — the QA panel
	// reads this to show the case's "compiled" state.
	Script    string       `json:"script"`
	CreatedAt string       `json:"created_at"`
	LatestRun *TestRunLite `json:"latest_run"`
}

type ListTestCasesResponse struct {
	TestCases []TestCaseResponse `json:"test_cases"`
}

func testCaseToResponse(c db.TestCase, latest *TestRunLite) TestCaseResponse {
	return TestCaseResponse{
		ID:         uuidToString(c.ID),
		IssueID:    uuidToString(c.IssueID),
		Title:      c.Title,
		Steps:      c.Steps,
		Expected:   c.Expected,
		Kind:       c.Kind,
		Source:     c.Source,
		AuthorType: c.AuthorType,
		Category:   c.Category,
		Script:     c.Script,
		CreatedAt:  c.CreatedAt.Time.Format(time.RFC3339),
		LatestRun:  latest,
	}
}

// GetIssueTestCases lists an issue's active test cases, each with its latest run.
// Project base scripts (issue_id NULL) run against this issue are appended after
// the issue's own cases — their verdicts (a FAIL is a regression) must render on
// the issue's QA panel, not vanish. Base cases carry issue_id "" in the response.
func (h *Handler) GetIssueTestCases(w http.ResponseWriter, r *http.Request) {
	issue, ok := h.loadIssueForUser(w, r, chi.URLParam(r, "id"))
	if !ok {
		return
	}
	cases, err := h.Queries.ListTestCasesForIssue(r.Context(), db.ListTestCasesForIssueParams{
		IssueID:     issue.ID,
		WorkspaceID: issue.WorkspaceID,
	})
	if err != nil {
		writeError(w, http.StatusInternalServerError, "failed to load test cases")
		return
	}
	if issue.ProjectID.Valid {
		baseCases, _ := h.Queries.ListAutomatedTestCasesForProject(r.Context(), db.ListAutomatedTestCasesForProjectParams{
			ProjectID:   issue.ProjectID,
			WorkspaceID: issue.WorkspaceID,
		})
		cases = append(cases, baseCases...)
	}
	runs, _ := h.Queries.ListLatestRunsForIssueCases(r.Context(), db.ListLatestRunsForIssueCasesParams{
		IssueID:     issue.ID,
		WorkspaceID: issue.WorkspaceID,
	})
	latest := make(map[string]*TestRunLite, len(runs))
	for _, run := range runs {
		latest[uuidToString(run.TestCaseID)] = &TestRunLite{
			ID:        uuidToString(run.ID),
			Status:    run.Status,
			RunSource: run.RunSource,
			CreatedAt: run.CreatedAt.Time.Format(time.RFC3339),
			Output:    run.Output,
			TracePath: run.TracePath,
		}
	}
	resp := ListTestCasesResponse{TestCases: make([]TestCaseResponse, 0, len(cases))}
	for _, c := range cases {
		resp.TestCases = append(resp.TestCases, testCaseToResponse(c, latest[uuidToString(c.ID)]))
	}
	writeJSON(w, http.StatusOK, resp)
}

type CreateTestCaseRequest struct {
	Title    string `json:"title"`
	Steps    string `json:"steps"`
	Expected string `json:"expected"`
	Kind     string `json:"kind"`
	Category string `json:"category"` // positive | negative; defaults to positive
}

// CreateIssueTestCase authors a manual test case for an issue (source=human).
func (h *Handler) CreateIssueTestCase(w http.ResponseWriter, r *http.Request) {
	issue, ok := h.loadIssueForUser(w, r, chi.URLParam(r, "id"))
	if !ok {
		return
	}
	userID, ok := requireUserID(w, r)
	if !ok {
		return
	}
	var req CreateTestCaseRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeError(w, http.StatusBadRequest, "invalid request body")
		return
	}
	if req.Title == "" {
		writeError(w, http.StatusBadRequest, "title is required")
		return
	}
	kind := "manual"
	if req.Kind == "automated" {
		kind = "automated"
	}
	category := "positive"
	if req.Category == "negative" {
		category = "negative"
	}
	c, err := h.Queries.CreateTestCase(r.Context(), db.CreateTestCaseParams{
		WorkspaceID: issue.WorkspaceID,
		IssueID:     issue.ID,
		ProjectID:   issue.ProjectID,
		Title:       req.Title,
		Steps:       req.Steps,
		Expected:    req.Expected,
		Kind:        kind,
		Source:      "human",
		AuthorType:  "member",
		AuthorID:    parseUUID(userID),
		Category:    category,
		Script:      "", // human-authored; empty triggers the background auto-compile hook below
	})
	if err != nil {
		writeError(w, http.StatusInternalServerError, "failed to create test case")
		return
	}
	h.publish(protocol.EventTestCasesChanged, uuidToString(issue.WorkspaceID), "member", userID, map[string]any{
		"issue_id": uuidToString(issue.ID),
	})
	// A human-authored automated case ships with no script; auto-compile it into a
	// runnable Playwright script in the background so run_test_cases executes it
	// deterministically. Detached, best-effort — gated inside maybeCompileTestCases.
	if kind == "automated" {
		go h.maybeCompileTestCases(context.Background(), issue)
	}
	writeJSON(w, http.StatusCreated, testCaseToResponse(c, nil))
}

// GetProjectTestCases lists a project's STANDING base test cases (issue_id
// NULL — the golden-path regression suite injected into every run_qa /
// run_test_cases), each with its latest run across all issues.
func (h *Handler) GetProjectTestCases(w http.ResponseWriter, r *http.Request) {
	wsUUID, ok := parseUUIDOrBadRequest(w, h.resolveWorkspaceID(r), "workspace id")
	if !ok {
		return
	}
	projUUID, ok := parseUUIDOrBadRequest(w, chi.URLParam(r, "id"), "project id")
	if !ok {
		return
	}
	project, err := h.Queries.GetProjectInWorkspace(r.Context(), db.GetProjectInWorkspaceParams{
		ID: projUUID, WorkspaceID: wsUUID,
	})
	if err != nil {
		writeError(w, http.StatusNotFound, "project not found")
		return
	}
	cases, err := h.Queries.ListTestCasesForProject(r.Context(), db.ListTestCasesForProjectParams{
		ProjectID:   project.ID,
		WorkspaceID: project.WorkspaceID,
	})
	if err != nil {
		writeError(w, http.StatusInternalServerError, "failed to load test cases")
		return
	}
	runs, _ := h.Queries.ListLatestRunsForProjectBaseCases(r.Context(), db.ListLatestRunsForProjectBaseCasesParams{
		ProjectID:   project.ID,
		WorkspaceID: project.WorkspaceID,
	})
	latest := make(map[string]*TestRunLite, len(runs))
	for _, run := range runs {
		latest[uuidToString(run.TestCaseID)] = &TestRunLite{
			ID:        uuidToString(run.ID),
			Status:    run.Status,
			RunSource: run.RunSource,
			CreatedAt: run.CreatedAt.Time.Format(time.RFC3339),
			Output:    run.Output,
			TracePath: run.TracePath,
		}
	}
	resp := ListTestCasesResponse{TestCases: make([]TestCaseResponse, 0, len(cases))}
	for _, c := range cases {
		resp.TestCases = append(resp.TestCases, testCaseToResponse(c, latest[uuidToString(c.ID)]))
	}
	writeJSON(w, http.StatusOK, resp)
}

// CreateProjectTestCase authors a standing base test case for a project —
// issue_id stays NULL, which is what ListAutomatedTestCasesForProject keys on.
// This is the ONLY write path that can produce base-suite rows: the issue-scoped
// create always pins issue_id. Kind defaults to "automated" (not "manual" like
// the issue endpoint) because only automated base cases are injected into
// run_qa / run_test_cases — a default-manual base case would be silently inert.
func (h *Handler) CreateProjectTestCase(w http.ResponseWriter, r *http.Request) {
	wsUUID, ok := parseUUIDOrBadRequest(w, h.resolveWorkspaceID(r), "workspace id")
	if !ok {
		return
	}
	projUUID, ok := parseUUIDOrBadRequest(w, chi.URLParam(r, "id"), "project id")
	if !ok {
		return
	}
	userID, ok := requireUserID(w, r)
	if !ok {
		return
	}
	project, err := h.Queries.GetProjectInWorkspace(r.Context(), db.GetProjectInWorkspaceParams{
		ID: projUUID, WorkspaceID: wsUUID,
	})
	if err != nil {
		writeError(w, http.StatusNotFound, "project not found")
		return
	}
	var req CreateTestCaseRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeError(w, http.StatusBadRequest, "invalid request body")
		return
	}
	if req.Title == "" {
		writeError(w, http.StatusBadRequest, "title is required")
		return
	}
	kind := "automated"
	if req.Kind == "manual" {
		kind = "manual"
	}
	category := "positive"
	if req.Category == "negative" {
		category = "negative"
	}
	c, err := h.Queries.CreateTestCase(r.Context(), db.CreateTestCaseParams{
		WorkspaceID: project.WorkspaceID,
		IssueID:     pgtype.UUID{}, // NULL — a base case belongs to the project, not an issue
		ProjectID:   project.ID,
		Title:       req.Title,
		Steps:       req.Steps,
		Expected:    req.Expected,
		Kind:        kind,
		Source:      "human",
		AuthorType:  "member",
		AuthorID:    parseUUID(userID),
		Category:    category,
		Script:      "", // human base case; compile-eligible on demand via /compile_tests
	})
	if err != nil {
		writeError(w, http.StatusInternalServerError, "failed to create test case")
		return
	}
	h.publish(protocol.EventTestCasesChanged, uuidToString(project.WorkspaceID), "member", userID, map[string]any{
		"project_id": uuidToString(project.ID),
	})
	writeJSON(w, http.StatusCreated, testCaseToResponse(c, nil))
}

type CreateTestRunRequest struct {
	Status string `json:"status"`
	Output string `json:"output"`
}

// CreateTestCaseRun records a manual run verdict for a test case (run_source=human).
func (h *Handler) CreateTestCaseRun(w http.ResponseWriter, r *http.Request) {
	workspaceID := h.resolveWorkspaceID(r)
	userID, ok := requireUserID(w, r)
	if !ok {
		return
	}
	wsUUID, ok := parseUUIDOrBadRequest(w, workspaceID, "workspace id")
	if !ok {
		return
	}
	caseUUID, ok := parseUUIDOrBadRequest(w, chi.URLParam(r, "id"), "test case id")
	if !ok {
		return
	}
	tc, err := h.Queries.GetTestCase(r.Context(), db.GetTestCaseParams{ID: caseUUID, WorkspaceID: wsUUID})
	if err != nil {
		writeError(w, http.StatusNotFound, "test case not found")
		return
	}
	var req CreateTestRunRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeError(w, http.StatusBadRequest, "invalid request body")
		return
	}
	status := req.Status
	switch status {
	case "pass", "fail", "skip", "blocked":
	default:
		writeError(w, http.StatusBadRequest, "status must be pass | fail | skip | blocked")
		return
	}
	run, err := h.Queries.CreateTestRun(r.Context(), db.CreateTestRunParams{
		WorkspaceID: tc.WorkspaceID,
		TestCaseID:  tc.ID,
		IssueID:     tc.IssueID,
		Status:      status,
		Output:      req.Output,
		RunSource:   "human",
		RunByType:   "member",
		RunByID:     parseUUID(userID),
	})
	if err != nil {
		writeError(w, http.StatusInternalServerError, "failed to record run")
		return
	}
	h.publish(protocol.EventTestCasesChanged, uuidToString(tc.WorkspaceID), "member", userID, map[string]any{
		"issue_id": uuidToString(tc.IssueID),
	})
	writeJSON(w, http.StatusCreated, map[string]any{
		"id":           uuidToString(run.ID),
		"test_case_id": uuidToString(run.TestCaseID),
		"status":       run.Status,
		"run_source":   run.RunSource,
		"created_at":   run.CreatedAt.Time.Format(time.RFC3339),
	})
}

// ArchiveTestCaseHandler soft-deletes a test case.
func (h *Handler) ArchiveTestCaseHandler(w http.ResponseWriter, r *http.Request) {
	workspaceID := h.resolveWorkspaceID(r)
	wsUUID, ok := parseUUIDOrBadRequest(w, workspaceID, "workspace id")
	if !ok {
		return
	}
	caseUUID, ok := parseUUIDOrBadRequest(w, chi.URLParam(r, "id"), "test case id")
	if !ok {
		return
	}
	if err := h.Queries.ArchiveTestCase(r.Context(), db.ArchiveTestCaseParams{ID: caseUUID, WorkspaceID: wsUUID}); err != nil {
		writeError(w, http.StatusInternalServerError, "failed to archive test case")
		return
	}
	w.WriteHeader(http.StatusNoContent)
}

// UpdateTestCaseRequest is the human-edit payload; any omitted field is left
// unchanged (partial update).
type UpdateTestCaseRequest struct {
	Title    *string `json:"title,omitempty"`
	Steps    *string `json:"steps,omitempty"`
	Expected *string `json:"expected,omitempty"`
	Kind     *string `json:"kind,omitempty"`
	Category *string `json:"category,omitempty"`
	Script   *string `json:"script,omitempty"`
}

// UpdateTestCaseHandler lets a QA engineer edit a test case (title/steps/
// expected/kind/category/script) from the cockpit. Workspace-scoped; only the
// provided fields change.
func (h *Handler) UpdateTestCaseHandler(w http.ResponseWriter, r *http.Request) {
	wsUUID, ok := parseUUIDOrBadRequest(w, h.resolveWorkspaceID(r), "workspace id")
	if !ok {
		return
	}
	caseUUID, ok := parseUUIDOrBadRequest(w, chi.URLParam(r, "id"), "test case id")
	if !ok {
		return
	}
	var req UpdateTestCaseRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeError(w, http.StatusBadRequest, "invalid request body")
		return
	}
	if req.Kind != nil && *req.Kind != "manual" && *req.Kind != "automated" {
		writeError(w, http.StatusBadRequest, "kind must be manual or automated")
		return
	}
	if req.Category != nil && *req.Category != "positive" && *req.Category != "negative" {
		writeError(w, http.StatusBadRequest, "category must be positive or negative")
		return
	}
	optText := func(p *string) pgtype.Text {
		if p == nil {
			return pgtype.Text{}
		}
		return pgtype.Text{String: strings.TrimSpace(*p), Valid: true}
	}
	updated, err := h.Queries.UpdateTestCase(r.Context(), db.UpdateTestCaseParams{
		ID:          caseUUID,
		WorkspaceID: wsUUID,
		Title:       optText(req.Title),
		Steps:       optText(req.Steps),
		Expected:    optText(req.Expected),
		Kind:        optText(req.Kind),
		Category:    optText(req.Category),
		Script:      optText(req.Script),
	})
	if err != nil {
		writeError(w, http.StatusNotFound, "test case not found")
		return
	}
	writeJSON(w, http.StatusOK, testCaseToResponse(updated, nil))
}
