package handler

import (
	"encoding/json"
	"net/http"
	"time"

	"github.com/go-chi/chi/v5"
	db "github.com/multica-ai/multica/server/pkg/db/generated"
	"github.com/multica-ai/multica/server/pkg/protocol"
)

// QA test cases — the QA team's test-management instruments. A case is authored
// by a QA human (this API) or generated by a QA-Squad agent (the gen_test_cases
// slice action, captured server-side). A run records one execution's verdict.

type TestRunLite struct {
	Status    string `json:"status"`
	RunSource string `json:"run_source"`
	CreatedAt string `json:"created_at"`
	// Output is the one-line evidence an agent reports per case (e.g. "embedded
	// browser unreachable") via the run_test_cases test-runs protocol. Surfaced
	// so a "blocked" verdict tells QA WHY, not just that it didn't run.
	Output string `json:"output,omitempty"`
}

type TestCaseResponse struct {
	ID         string       `json:"id"`
	IssueID    string       `json:"issue_id"`
	Title      string       `json:"title"`
	Steps      string       `json:"steps"`
	Expected   string       `json:"expected"`
	Kind       string       `json:"kind"`
	Source     string       `json:"source"`
	AuthorType string       `json:"author_type"`
	Category   string       `json:"category"` // positive | negative
	CreatedAt  string       `json:"created_at"`
	LatestRun  *TestRunLite `json:"latest_run"`
}

type ListTestCasesResponse struct {
	TestCases []TestCaseResponse `json:"test_cases"`
}

func testCaseToResponse(c db.TestCase, latest *TestRunLite) TestCaseResponse {
	return TestCaseResponse{
		ID:         uuidToString(c.ID),
		IssueID:    uuidToString(c.IssueID),
		Title:      c.Title,
		Steps:      c.Steps,
		Expected:   c.Expected,
		Kind:       c.Kind,
		Source:     c.Source,
		AuthorType: c.AuthorType,
		Category:   c.Category,
		CreatedAt:  c.CreatedAt.Time.Format(time.RFC3339),
		LatestRun:  latest,
	}
}

// GetIssueTestCases lists an issue's active test cases, each with its latest run.
func (h *Handler) GetIssueTestCases(w http.ResponseWriter, r *http.Request) {
	issue, ok := h.loadIssueForUser(w, r, chi.URLParam(r, "id"))
	if !ok {
		return
	}
	cases, err := h.Queries.ListTestCasesForIssue(r.Context(), db.ListTestCasesForIssueParams{
		IssueID:     issue.ID,
		WorkspaceID: issue.WorkspaceID,
	})
	if err != nil {
		writeError(w, http.StatusInternalServerError, "failed to load test cases")
		return
	}
	runs, _ := h.Queries.ListLatestRunsForIssueCases(r.Context(), db.ListLatestRunsForIssueCasesParams{
		IssueID:     issue.ID,
		WorkspaceID: issue.WorkspaceID,
	})
	latest := make(map[string]*TestRunLite, len(runs))
	for _, run := range runs {
		latest[uuidToString(run.TestCaseID)] = &TestRunLite{
			Status:    run.Status,
			RunSource: run.RunSource,
			CreatedAt: run.CreatedAt.Time.Format(time.RFC3339),
			Output:    run.Output,
		}
	}
	resp := ListTestCasesResponse{TestCases: make([]TestCaseResponse, 0, len(cases))}
	for _, c := range cases {
		resp.TestCases = append(resp.TestCases, testCaseToResponse(c, latest[uuidToString(c.ID)]))
	}
	writeJSON(w, http.StatusOK, resp)
}

type CreateTestCaseRequest struct {
	Title    string `json:"title"`
	Steps    string `json:"steps"`
	Expected string `json:"expected"`
	Kind     string `json:"kind"`
	Category string `json:"category"` // positive | negative; defaults to positive
}

// CreateIssueTestCase authors a manual test case for an issue (source=human).
func (h *Handler) CreateIssueTestCase(w http.ResponseWriter, r *http.Request) {
	issue, ok := h.loadIssueForUser(w, r, chi.URLParam(r, "id"))
	if !ok {
		return
	}
	userID, ok := requireUserID(w, r)
	if !ok {
		return
	}
	var req CreateTestCaseRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeError(w, http.StatusBadRequest, "invalid request body")
		return
	}
	if req.Title == "" {
		writeError(w, http.StatusBadRequest, "title is required")
		return
	}
	kind := "manual"
	if req.Kind == "automated" {
		kind = "automated"
	}
	category := "positive"
	if req.Category == "negative" {
		category = "negative"
	}
	c, err := h.Queries.CreateTestCase(r.Context(), db.CreateTestCaseParams{
		WorkspaceID: issue.WorkspaceID,
		IssueID:     issue.ID,
		ProjectID:   issue.ProjectID,
		Title:       req.Title,
		Steps:       req.Steps,
		Expected:    req.Expected,
		Kind:        kind,
		Source:      "human",
		AuthorType:  "member",
		AuthorID:    parseUUID(userID),
		Category:    category,
	})
	if err != nil {
		writeError(w, http.StatusInternalServerError, "failed to create test case")
		return
	}
	h.publish(protocol.EventTestCasesChanged, uuidToString(issue.WorkspaceID), "member", userID, map[string]any{
		"issue_id": uuidToString(issue.ID),
	})
	writeJSON(w, http.StatusCreated, testCaseToResponse(c, nil))
}

type CreateTestRunRequest struct {
	Status string `json:"status"`
	Output string `json:"output"`
}

// CreateTestCaseRun records a manual run verdict for a test case (run_source=human).
func (h *Handler) CreateTestCaseRun(w http.ResponseWriter, r *http.Request) {
	workspaceID := h.resolveWorkspaceID(r)
	userID, ok := requireUserID(w, r)
	if !ok {
		return
	}
	wsUUID, ok := parseUUIDOrBadRequest(w, workspaceID, "workspace id")
	if !ok {
		return
	}
	caseUUID, ok := parseUUIDOrBadRequest(w, chi.URLParam(r, "id"), "test case id")
	if !ok {
		return
	}
	tc, err := h.Queries.GetTestCase(r.Context(), db.GetTestCaseParams{ID: caseUUID, WorkspaceID: wsUUID})
	if err != nil {
		writeError(w, http.StatusNotFound, "test case not found")
		return
	}
	var req CreateTestRunRequest
	if err := json.NewDecoder(r.Body).Decode(&req); err != nil {
		writeError(w, http.StatusBadRequest, "invalid request body")
		return
	}
	status := req.Status
	switch status {
	case "pass", "fail", "skip", "blocked":
	default:
		writeError(w, http.StatusBadRequest, "status must be pass | fail | skip | blocked")
		return
	}
	run, err := h.Queries.CreateTestRun(r.Context(), db.CreateTestRunParams{
		WorkspaceID: tc.WorkspaceID,
		TestCaseID:  tc.ID,
		IssueID:     tc.IssueID,
		Status:      status,
		Output:      req.Output,
		RunSource:   "human",
		RunByType:   "member",
		RunByID:     parseUUID(userID),
	})
	if err != nil {
		writeError(w, http.StatusInternalServerError, "failed to record run")
		return
	}
	h.publish(protocol.EventTestCasesChanged, uuidToString(tc.WorkspaceID), "member", userID, map[string]any{
		"issue_id": uuidToString(tc.IssueID),
	})
	writeJSON(w, http.StatusCreated, map[string]any{
		"id":          uuidToString(run.ID),
		"test_case_id": uuidToString(run.TestCaseID),
		"status":      run.Status,
		"run_source":  run.RunSource,
		"created_at":  run.CreatedAt.Time.Format(time.RFC3339),
	})
}

// ArchiveTestCaseHandler soft-deletes a test case.
func (h *Handler) ArchiveTestCaseHandler(w http.ResponseWriter, r *http.Request) {
	workspaceID := h.resolveWorkspaceID(r)
	wsUUID, ok := parseUUIDOrBadRequest(w, workspaceID, "workspace id")
	if !ok {
		return
	}
	caseUUID, ok := parseUUIDOrBadRequest(w, chi.URLParam(r, "id"), "test case id")
	if !ok {
		return
	}
	if err := h.Queries.ArchiveTestCase(r.Context(), db.ArchiveTestCaseParams{ID: caseUUID, WorkspaceID: wsUUID}); err != nil {
		writeError(w, http.StatusInternalServerError, "failed to archive test case")
		return
	}
	w.WriteHeader(http.StatusNoContent)
}
