// QA test cases — the QA team's test-management instruments. A case is authored
// by a QA human or generated by a QA-Squad agent (gen_test_cases); a run records
// one execution's verdict. See migration 135.

export interface TestRunLite {
  status: string; // pass | fail | skip | blocked
  run_source: string; // human | agent
  created_at: string;
  output: string; // agent's one-line evidence/reason; empty for human-recorded runs
}

export interface TestCase {
  id: string;
  issue_id: string;
  title: string;
  steps: string;
  expected: string;
  kind: string; // manual | automated
  source: string; // human | agent
  author_type: string;
  created_at: string;
  latest_run: TestRunLite | null;
}

export interface ListTestCasesResponse {
  test_cases: TestCase[];
}

export interface CreateTestCaseRequest {
  title: string;
  steps?: string;
  expected?: string;
  kind?: string;
}

export interface CreateTestRunRequest {
  status: string;
  output?: string;
}
